### ISSUE TITLE
Unicode RRset creation results in 500

### ISSUE THREAD

**Issue by My1** [desec-io/desec-stack#102]
when you create an RRSet with a unicode subname, the server takes a while and throws a 500.

while it isnt a problem that the server doesnt like unicode domains, the handling is suboptimal.

There should be 1 of 2 behaviors:

1) Accept unicode domains
2) check for unicode domains and reject them and tell the user to use Punycode.

**Comment by peterthomassen** [comment]
Location

    File "./desecapi/views.py" in create
      199.             return super().create(request, *args, **kwargs)

Exception

    OperationalError at /api/v1/domains/{domain}/rrsets/
    (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='")

**Comment by peterthomassen** [comment]
@nils-wisiol Do you think it is a good idea to support unicode subdomains?

**Comment by My1** [comment]
honestly I would say that it's probably at least easier to force puny especially because of a few things:

1) uniqueness checking
2) which format to push through the API to the User

3) which standard to use?
I mean there are 3 standards right now:
IDNA 2003
UTS46 (an intermediate thing)
IDNA 2008

while UTS tries to find a way to make the transition easier the difference between the 2003 and 2008 versions are in a few characters, most notably in german the ß character which is resolved to ss in 2003 and kept unicode and converted into puny instead in the 2008 version, also we have the greek final sigma, which gets resolved to normal sigma in 2003, while being kept and converted to puny as-is.

Similar story for the Zero-width Joiners and non-joiners commonly found in arabic or indic languages.
2003 tries to simplify by knocking them both out of business, while 2008 keeps them, with a limitation that these "context joiners" may only be used in certain sequences of arabic or indic characters, probably only in areas where these have any optical effect, while in contrast a<ZWNJ>b will look the same as ab, and therefore not allowed.

**Comment by nils-wisiol** [comment]
I'm not sure what's the way to go, right now I'd opt for whatever is supported by pdns in order to decrease the workload on our side.

**Comment by My1** [comment]
well PDNS obviously does puny (which isnt a surprise) but it whether it supports full unicode, no Idea

**Comment by nils-wisiol** [comment]
Although this is something that does not affect newer systems, we also fixed this in the desec.io production system. We had to convert all tables to `utf8mb4` collation and encoding (mariadb's real utf8). For production conversion, I used

    alter table auth_group convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table auth_group_permissions convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table auth_permission convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table desecapi_domain convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table desecapi_donation convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table desecapi_token convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table desecapi_user convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table django_admin_log convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table django_content_type convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table django_migrations convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table django_session convert to character set utf8mb4 collate utf8mb4_general_ci;

    alter table desecapi_rr drop foreign key desecapi_rr_rrset_id_675bf73d_fk;

    alter table desecapi_rr convert to character set utf8mb4 collate utf8mb4_general_ci;
    alter table desecapi_rrset convert to character set utf8mb4 collate utf8mb4_general_ci;

    ALTER TABLE desecapi_rr ADD CONSTRAINT desecapi_rr_rrset_id_675bf73d_fk FOREIGN KEY (rrset_id) REFERENCES desecapi_rrset(id);

To verify this is working (we also added e2e tests for new systems), I used 

    http https://desec.io/api/v1/domains/nils-wisiol.de/rrsets/ \
    Authorization:"Token secrettoken" \
    subname:='"utf8mb4verify"' \
    type:='"TXT"' \
    ttl:=60 \
    records:='["\"我住在柏林💩\""]'

which is accepted by desec/pdns. (I added the pile of poo just to be sure.) You can verify the output by sending a query using `host -t TXT utf8mb4verify.nils-wisiol.de` and then decode the answer using, e.g., python3:

    bytes([230,136,145,228,189,143,229,156,168,230,159,143,230,158,151,240,159,146,169]).decode()

I consider this resolved now, if the problem persists, please reopen.

**Comment by My1** [comment]
I just tried doing some U2F and I got shot down with a 422 (well at least it isnt a 500)


![screenshot 505](https://user-images.githubusercontent.com/6696524/45811453-6db9a280-bccd-11e8-9bb1-44120eb23bcc.png)

results in: {"detail":"Name '\\227\\131\\134\\227\\130\\185\\227\\131\\136.domain.tld.' contains unsupported characters"}


but creating a TXT with some Japanese content on a "normal" subname (or a Puny) works totally fine.

![screenshot 506](https://user-images.githubusercontent.com/6696524/45812136-3946e600-bccf-11e8-90c8-0754f3db2549.png)

 so we need either a fix on that side or a doc change.

**Comment by nils-wisiol** [comment]
utf8 zone (domain) names are not supported:

    http https://desec.io/api/v1/domains/nils-wisiol.de/rrsets/ \
    Authorization:"Token secrettoken" \
    subname:='"你好.utf8mb4verify"' \
    type:='"TXT"' ttl:=60 records:='["\"perfectly friendly ascii string\""]'

will be rejected

**Comment by My1** [comment]
which (as said) isnt nessecarily a problem but it would definitely be helpful to include that somewhere in the docs, that you have to go Puny for Unicode domains. (and as you can see above, a client can do the presentation and conversion of the whole thing.

**Comment by nils-wisiol** [comment]
We do support IDN domain names though:

    $ dig +short TXT xn--6qq79v.utf8mb4.nils-wisiol.de @ns1.desec.io 
    "\230\136\145\228\189\143\229\156\168\230\159\143\230\158\151\240\159\146\169"

where xn--6qq79v represents 你好

**Comment by My1** [comment]
That's what I've been saying the whole time. For Unicode domains you need to use Punycode
https://en.wikipedia.org/wiki/Punycode

my point is just that the fact that you have to use that encoding should be noted somewhere in the docs.

**Comment by nils-wisiol** [comment]
moved to new issue #123 

no docs change for now, instead we will hide the puny names from the api user

**Comment by My1** [comment]
okay, now we have a decision on this, which is great. I'll check out the 123 (nice number btw)
