### ISSUE TITLE
Future Enhancement: Signature Authentication

### ISSUE THREAD

**Issue by My1** [desec-io/desec-stack#104]
This will be probably be a thing for the FAR future, but I'll still share it.

one of the few things that slightly bug me is that, even with HTTPS, that you blast the Authentication key/token/whatever-one-may-call-it into the internet with each request, which obviously isnt really a good idea for obvious reasons.

by using signatures like HMAC though, one could easily do authentication of a request, while on the other hand keeping the key on the server (in even more crazy setups even dump it on a smartcard which makes sure the key cant be stolen).

making signature uniqueness is relatively simple by introducing the time and nonce parameter into the Request JSON, which will be filled with unixtime and obviously, a nonce.

Considering the header doesnt really contain any intresting information that would need to be signed the signed string could for example be the following:

`METHOD URL|BODY-DATA`

METHOD is the HTTP Method (POST, PUT, etc), the rest being self-explanatory.

for sake of simplicity the pipe (or whatever seperator between the body data and the URL) would always be there
The reasoning for a pipe as a seperator is that this is probably a character that wont appear even if other content types like XML would someday become a thing.

with the key obviously being the token.

the newer auth header for signatures could be done like this:

`Authorization: Signature USER-ID HASH-TYPE SIGNATURE`

where USER-ID would be something to identify the user and SIGNATURE obviously enough the signature.

Example Signatures:

Request: GET to https://desec.io/api/v1/domains/ (just list the account domains)
Body Data: {"time":"124548624","nonce":"abcdef"}
Token: 0123456789abcdef
User-ID: 1
Hash-Type: SHA-512

String to be signed:
`GET https://desec.io/api/v1/domains/|{"time":"124548624","nonce":"abcdef"}`
Signature:
Key interpreted as normal text: `f34fc6267057998dd9ec3ebd4e133dcfb11bcc017aee5e9eb05bdc753fc4282c9aa07814dd16bf45102cc751d149ee3c6671a1202facbb365705d43b8f84b95b`

Key interpreted as hex and converted to binary:
`67f880f680c1167a9501335b06447a3913030cfbeeb4c97fe0fe94d394fd2d32f71b42d883b6e285be2bdecec9f073c71e587f5c98c01132c7abc128b53a283a`

Resulting header:

`Authorization: Signature 1 SHA-512 f34fc6267057998dd9ec3ebd4e133dcfb11bcc017aee5e9eb05bdc753fc4282c9aa07814dd16bf45102cc751d149ee3c6671a1202facbb365705d43b8f84b95b`

or

`Authorization: Signature 1 SHA-512 67f880f680c1167a9501335b06447a3913030cfbeeb4c97fe0fe94d394fd2d32f71b42d883b6e285be2bdecec9f073c71e587f5c98c01132c7abc128b53a283a`

(obviously enough there would be only one way at the end but as I dont know which will be taken I considered both).

This could be optional maybe enforced even later, but if it's optional, then time nonce and signature will have an atomic relationship, meaning if you include one, you need to include all.

**Comment by peterthomassen** [comment]
Thank you for this proposal.

We are not going to implement it because

- it complicates things a lot
- it does not increase the security level given that we are using state-of-the-art TLS
- downgrade attack to current token would be possible, as we can't just throw out all clients not supporting the signature procedure

In the future, we'll consider token expiration times that depend on the resource they are used for (e.g. dynDNS would have a longer expiration time than a session token). Take a look at OAuth to learn more about this sort of concept.

**Comment by My1** [comment]
I agree that it does complicate things, but it is a LOT less bad than what [Twitter](https://developer.twitter.com/en/docs/basics/authentication/guides/authorizing-a-request) is doing (I speak from experience, just doing an oauth sign in requires THREE of those crazily signed requests).

downgrade, well how do you suppose a downgrade would work?
I mean even if it is optional (which totally makes sense), the ones who are wary (or just crazy) enough to sign probably wont automatically downgrade to sending the token?

so, the only ones that could be attacked would be those who dont use the signature, while users with a signature can evade.

state of the art TLS is nice but there are 2 BIG problems:

1) misissuances
2) the broken revocation
