### ISSUE TITLE
api: Sending unicode characters in subname during rrsets/ POST causes 500

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#108]
Error:

    OperationalError at /api/v1/domains/{domain}/rrsets/
    (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='")

Fix: require subname to contain legal characters only

**Comment by My1** [comment]
sorry, but I opened one a while ago.
#102

**Comment by peterthomassen** [comment]
thanks, duplicate.
