### ISSUE TITLE
Make user's email address writable through API

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#120]
Let the user change her own email address

@peterthomassen Should we enforce existence of the new address?

**Comment by peterthomassen** [comment]
I think we should, yes. Otherwise, people loose the ability to use customer support.

**Comment by nils-wisiol** [comment]
we don't check when people first register with the API. We send an login token to the registered email address, but you can do without. (The login token is also included in the reply to email address and password on `/auth/token/create`.)

**Comment by peterthomassen** [comment]
The email address is already writable (via `PUT` or `PATCH` to `api/v1/auth/me/`).

**Comment by nils-wisiol** [comment]
Then let's convert this into a docs issue :-)

On September 18, 2018 4:45:05 PM GMT+02:00, Peter Thomassen <notifications@github.com> wrote:
>The email address is already writable (via `PUT` or `PATCH` to
>`api/v1/auth/me/`).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/desec-io/desec-stack/issues/120#issuecomment-422422359

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
