### ISSUE TITLE
api: remove timezone support

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#122]
Server-side timezone awareness is unnecessary complexity. We should deal with timezone conversions at the presentation layer (client).

We're not using the functionality anyways (it's merely enabled so that one has to use Django's `now()` function instead of the standard Python `datetime.datetime.now()`).

**Comment by My1** [comment]
I wasnt even aware that there were any times in here, but sure removing timezone support does make sense as you dont have to guess what timezone the server is using at the time and just using unixtime is simple and works.
