### ISSUE TITLE
www: improve API rate limit

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#130]
The API rate limit is currently set at `30r/s` which seems a bit high for requests forwarded to pdns; for tests concerning account management (creation, login etc.) is it fine. The high rate that is currently allowed is required for the test suite to run properly.

The rate limit needs to be adjusted such that requests passed to pdns are constrained more tightly. This concerns requests under `/api/v1/domains/` in particular, maybe even independent of IP address. Further load testing on pdns has to be done.

We might want to define exceptions for automated tests, i.e. origin IP ranges local to the docker installation. One possible solution is described [here](https://serverfault.com/questions/177461/how-to-rate-limit-in-nginx-but-including-excluding-certain-ip-addresses).

**Comment by peterthomassen** [comment]
This appears quite handy: https://django-ratelimit.readthedocs.io/en/stable/

**Comment by My1** [comment]
the intresting question will obviously be how many are allowed after the real fix (and I probably should check my hobby webinterface for whether or not it uses multiple calls on one site), but generally I doubt that more than 2 or 3 per sec would be needed in non-automated scenarios

**Comment by peterthomassen** [comment]
see also https://www.django-rest-framework.org/api-guide/throttling/
