### ISSUE TITLE
Rethink Signup Workflow

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#155]
Possible improvements:

- one sign up form for all use cases
- multiple sign up forms, each for an individual use case

It's important to communicate the difference of password and token.

**Comment by nils-wisiol** [comment]
Also, send one email only, to avoid spam filtering

**Comment by peterthomassen** [comment]
One sign-up endpoint for all use cases. Accepts email address and password, optionally domain name. In any case, email address has to be verified. If domain name is given, verification will trigger domain creation. On failure, account is deleted so user can start over. Being implemented in #222.
