### ISSUE TITLE
Add Locking/Unlocking mechanism (needs good integration with the REST API)

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#162]
Unlocking with the Captcha is, strictly speaking, not part of the REST API: it does not rely on the REST principles, nor does it use `rest_framework`.

One symptom is that `rest_framework`'s `reverse()`ing URLs cannot be applied, as the `request` object does not carry versioning information.

Proposed solution: either integrate the unlocking mechanism fully into the API, or remove it entirely from the API (including using URLs not under `/api/v1/`).

**Comment by peterthomassen** [comment]
I think removing the mechanism is not an option, so let's integrate it.

How about having the interface do something like

1. `PATCH auth/me/ "locked":=null`, some challenge-response included to remove `locked` flag only
2. `GET domains/?published=null` to get domains
3. `PUT domains/:domain/` for each unpublished one (should one be one or so, maybe add constraint that it is newer than the lock)

This would require some frontend stuff and also implementing `PUT` on `DomainDetail`, but it would decouple things. Also, having `PUT` as a means to publish may be useful later.

**Comment by nils-wisiol** [comment]
I meant removing the unlocking captcha from the API namespace and code, moving same or equivalent functionality somewhere else

**Comment by peterthomassen** [comment]
The captcha package we're using is unmaintained. Here's an overview of more up-to-date ones: https://djangopackages.org/grids/g/captcha/

**Comment by peterthomassen** [comment]
We're in the process of removing the locking/unlocking mechanism and replacing it with the invitation-only approach. I therefore removed this issue from the Launch project and renamed it so that it will be useful later on.

**Comment by peterthomassen** [comment]
The locking/unlocking mechanism (`unlock/` endpoint with `UnlockForm` etc.) does not exist anymore, so this issue is obsolete.
