### ISSUE TITLE
Introduce Consistent Status Codes for Validation Errors

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#164]
Currently, if validation of subname or type fails in Django, we send status 404 (see URL conf). On the other hand, if validation fails in pdns, we send 422.

Unfortunately, I do not have a subname handy that will pass the URL conf but fail pdns and hence exhibit the inconsistency corner case.

**Comment by peterthomassen** [comment]
`*www` is probably such a subname (not the missing dot)

**Comment by peterthomassen** [comment]
This is not an issue anymore, as we don't do subname validation in the URL config of the RRsetDetail endpoint anymore, but pass it on to the view which then receives an empty queryset from the database. We agreed that that's fine.
