### ISSUE TITLE
Invalid IP Address Value Results in Server Error

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#168]
Internal Server Error: /api/v1/unlock/user/████████████@gmail.com

PdnsException at /api/v1/unlock/user/████████████@gmail.com
Record n████████████m.dedyn.io./A '<3█████1███████.1>': Parsing record content (try 'pdnsutil check-zone'): while parsing IP address, expected digits at position 0 in '<3█████1███████.1>'

Request Method: POST
Request URL: https://desec.io/api/v1/unlock/user/████████████@gmail.com
Django Version: 2.1.7
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.7.2
Python Path: ['.', '', '/usr/local/lib/python37.zip', '/usr/local/lib/python3.7', '/usr/local/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/site-packages']
Server time: ███████████████████████████████████
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'rest_framework',
 'djoser',
 'desecapi')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware')

Traceback:

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "./desecapi/views.py" in unlock
  541.                     user.unlock()

File "./desecapi/models.py" in unlock
  126.             domain.sync_to_pdns()

File "./desecapi/models.py" in sync_to_pdns
  192.             self._publish()

File "/usr/local/lib/python3.7/contextlib.py" in inner
  74.                 return func(*args, **kwds)

File "./desecapi/models.py" in _publish
  358.             pdns.set_rrsets(self, rrsets)

File "./desecapi/pdns.py" in set_rrsets
  140.     _pdns_patch('/zones/' + domain.pdns_id, data)

File "./desecapi/pdns.py" in _pdns_patch
  54.         raise PdnsException(r)

Exception Type: PdnsException at /api/v1/unlock/user/████████████@gmail.com
Exception Value: Record n████████████m.dedyn.io./A '<3█████1███████.1>': Parsing record content (try 'pdnsutil check-zone'): while parsing IP address, expected digits at position 0 in '<3█████1███████.1>'
Request information:
USER: [unable to retrieve the current user]

GET: No GET data

POST:
csrfmiddlewaretoken = '████████████████████████████'
g-recaptcha-response = '██████████████████████████████████████████'

FILES: No FILES data

COOKIES:
csrftoken = '██████████████████████████████████████████'

META:
CONTENT_LENGTH = '440'
CONTENT_TYPE = 'application/x-www-form-urlencoded'
CSRF_COOKIE = '███████████████████████████████████'
DOCUMENT_ROOT = '/etc/nginx/html'
HTTPS = 'on'
HTTP_ACCEPT = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE = 'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7'
HTTP_CACHE_CONTROL = 'max-age=0'
HTTP_CONTENT_LENGTH = '440'
HTTP_CONTENT_TYPE = 'application/x-www-form-urlencoded'
HTTP_COOKIE = '████████████████████████████████████████████████████████'
HTTP_HOST = 'desec.io'
HTTP_ORIGIN = 'https://desec.io'
HTTP_REFERER = 'https://desec.io/api/v1/unlock/user/████████████@gmail.com'
HTTP_UPGRADE_INSECURE_REQUESTS = '1'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/████████ (KHTML, like Gecko) Chrome/72.████████ Safari/████████'
PATH_INFO = '/api/v1/unlock/user/████████████@gmail.com'
QUERY_STRING = ''
REMOTE_ADDR = '███████████████████████████████████'
REMOTE_PORT = '███████'
REQUEST_METHOD = 'POST'
REQUEST_SCHEME = 'https'
REQUEST_URI = '/api/v1/unlock/user/████████████@gmail.com'
SCRIPT_NAME = ''
SERVER_NAME = 'desec.io'
SERVER_PORT = '443'
SERVER_PROTOCOL = 'HTTP/2.0'

**Comment by peterthomassen** [comment]
This only happened in the context of writing to a locked account and was fixed by #147.
