### ISSUE TITLE
Revise Permissions and Validations

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#186]
Currently, much validation/permission checking happens in the `perform_create` view of the `DomainList` view. Some of it could be considered a user's permission (such as creating public suffix domains), some of it could be considered validation (such as the domain name validation according to the dyn flag).

This issue is to move all permission checks to where they belong, supposedly rest framework permission classes, if possible. One major problem is that object permissions are hard to run when creating new objects, so we need to figure out a way to do that.

Some other views have similar issues, e.g. the type check on the RRSet endpoint.

**Comment by peterthomassen** [comment]
This has almost completely been done in the meantime (with the exception of ~5 lines of code, which IMO doesn't warrant keeping this ticket open).
