### ISSUE TITLE
Remove /dns endpoint?

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#193]
Do we need to keep the `/dns` endpoint? It is currently (pre-launch) mentioned in dyn welcome emails for domain status checking, but the output is sometimes misleading (e.g. for locked users). Also, it's a misnomer (`/query` or something like that would fit better).

We should discuss in the context of the website relaunch whether such an endpoint is needed, and how it should look like. For example, it may be better to just offer an endpoint that gives some rough status information from the api database (without issuing a DNS query).

**Comment by nils-wisiol** [comment]
I'd like to add that I do have some security concerns with passing user input to the dns library

**Comment by peterthomassen** [comment]
We can simply replace the link in the welcome email with this one: https://digwebinterface.com/?hostnames=$DOMAIN&type=ANY&ns=auth

Then, we can remove the endpoint.

I was considering to add a redirect from the old URL, but then realized that the old link is actually a deeplink into our web site (and not a link to the `/dns` endpoint). I would rather not impose any functionality constraints on the web site. I think putting the above link directly in the email is fine.

**Comment by peterthomassen** [comment]
Decided with Nils that external stuff like digwebinterface.com is not desirable. Also, their output is not very user-friendly.

Instead, implementing a new script that allows client-side checking using the regular API.
