### ISSUE TITLE
empty ${DESECSTACK_API_PSL_RESOLVER} breaks POSTing domains

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#198]
Setting `${DESECSTACK_API_PSL_RESOLVER}` to empty (or not setting it at all) in `.env` will result in a 30s delay when posting to `api/v1/domains` endpoint, then raise a timeout exception, which results in a 500 error.

Call stack:

	api_1       | Internal Server Error: /api/v1/domains/
	api_1       | Traceback (most recent call last):
	api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
	api_1       |     response = get_response(request)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
	api_1       |     response = self.process_exception_by_middleware(e, request)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
	api_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
	api_1       |     return view_func(*args, **kwargs)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
	api_1       |     return self.dispatch(request, *args, **kwargs)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
	api_1       |     response = self.handle_exception(exc)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
	api_1       |     self.raise_uncaught_exception(exc)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
	api_1       |     response = handler(request, *args, **kwargs)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/rest_framework/generics.py", line 244, in post
	api_1       |     return self.create(request, *args, **kwargs)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 21, in create
	api_1       |     self.perform_create(serializer)
	api_1       |   File "./desecapi/views.py", line 119, in perform_create
	api_1       |     public_suffix = self.psl.get_public_suffix(domain_name)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/psl_dns/querier.py", line 42, in get_public_suffix
	api_1       |     public_suffix = self._get_public_suffix_raw(domain)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/psl_dns/querier.py", line 30, in _get_public_suffix_raw
	api_1       |     answer = self.query(domain, dns.rdatatype.PTR)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/psl_dns/querier.py", line 93, in query
	api_1       |     answer = self.resolver.query(qname, rdatatype, lifetime=self.timeout)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/dns/resolver.py", line 992, in query
	api_1       |     timeout = self._compute_timeout(start, lifetime)
	api_1       |   File "/usr/local/lib/python3.7/site-packages/dns/resolver.py", line 799, in _compute_timeout
	api_1       |     raise Timeout(timeout=duration)
	api_1       | dns.exception.Timeout: The DNS operation timed out after 30.001466035842896 seconds
	api_1       | [pid: 250|app: 0|req: 1/1] 172.16.0.1 () {44 vars in 629 bytes} [Thu May 30 17:31:09 2019] POST /api/v1/domains/ => generated 14294 bytes in 30219 msecs (HTTP/1.1 500) 2 headers in 102 bytes (1 switches on core 0)

Expected behavior: according to README: use the system's resolver. (I confirmed in my setup that the resolver is working; however wireshark did not show a DNS query to somewhere after trying to post a domain.)

Steps to reproduce: clean master, clean builds, empty database, unset psl resolver (obviously). Then post to the domains endpoint.

Workaround: set it to 9.9.9.9 or competitors.

**Comment by autodiscover** [comment]
Actually, this is solved by bumping the psl-dns dependency from 1.0rc2 to 1.0rc3.

To reduce the number of merges/deployments on PSL-related stuff, maybe we can do this when the psl-dns code review is done (so the version would change to 1.0 final)?

**Comment by peterthomassen** [comment]
As described, this was fixed in psl-dns a while ago, and we're now using that newer version. I just tried and can't reproduce the issue now. Feel free to reopen if it resurfaces.
