### ISSUE TITLE
require new domains to be "well-formed"

### ISSUE THREAD

**Issue by zervnet** [desec-io/desec-stack#2]
some of the more common subdomains should be reserved. This has several reasons:

- secures some commonly used subdomains for future growth
- some subdomains could be used to obfuscate the real URL or trick/confuse a user
- the subdomain www. should be reserved .... (www.dedyn.io)

http://wiki.dwscoalition.org/notes/List_of_reserved_subdomains shows possible subdomains to reserve, but not all subdomains on this list seem to be necessary woth of reserving.

**Comment by peterthomassen** [comment]
Also, block `_tcp` and the like

**Comment by peterthomassen** [comment]
Also, introduce a setting in `.env` to require new domains to have a specific suffix (e.g. `.dedyn.io`)

**Comment by peterthomassen** [comment]
I added a check requiring new domains to match a regular expression. It is the same one we're using in the `static` client, see [desec-static:dyndns-signup-form.jade#L26](https://github.com/desec-io/desec-static/blob/master/app/partials/dyndns-signup-form.jade#L26). Please see the commit cfbfbe0cde33e2715ee69c045bd9a5bc85464e8e.

The regular expression used is `^[A-Za-z][A-Za-z0-9-]*\.dedyn\.io$`. In addition, the domain name is not allowed to contain `--`. While technically, that would be legal, labels beginning with `xn--` are IDN representations and need to fulfill additional constraints, and I didn't want to get into that mess. And who knows, maybe there will be special reserved prefixes with `--` in the future.

This commit breaks tests that are trying to create other domains, like `testCanPostDomains()` (trying to create `[randomString].de`). Clearly, creation of other domains is a desirable functionality for the future. The question is how to lock it down now, while not barring the way to the future.

The `dyn` property of the domain object is useless for this purpose, as it is supplied by the user. (In fact, I'm not sure why it exists.) The set of domains a user is allowed to create in fact will depend on the domain owner, and it seems to me that `dyn` should be a property of the user, not of the domain. Is this the right way to move forward?

If we want to deploy this quickly (which I think we should), we can disable the failing tests for the moment. Alternatively, we could limit ourselves to blacklist only domains with, for instance, `_` and `--` in them, regardless of the `dedyn.io` suffix. This, however, would allow users to place domains that we are not and will not be authoritative for.

**Comment by peterthomassen** [comment]
@zervnet Addressing your suggestions:

  - Can you elaborate what sort of names you think should be reserved for future growth?
  - The above commit is going to allow alpha-numeric names only, without dots. This gives basic protection against tricks with UTF-8 characters that look similar to ASCII ones, or things like `www.webmail.fu-berlin.dedyn.io`.
  - `www.dedyn.io` is already reserved (not in the code, but it is a zone that exists and therefore cannot be claimed by another user).

**Comment by zervnet** [comment]
I would reserve the subdomains support, login, abuse and api (not sure about that one). 
(it's a kind of arbitrary list and could be of any length, but I guess those 4 would be worth reserving)

**Comment by peterthomassen** [comment]
@zervnet I agree the list is arbitrary, which is why I would vote against it. Unless @nils-wisiol presents another opinion, I will consider this resolved.

@nils-wisiol We still need to discuss how to proceed with the issues outlined in https://github.com/desec-io/desec-stack/issues/2#issuecomment-269246728.
