### ISSUE TITLE
Configure reporting for HTTP security headers

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#203]
- Consider headers already configured
- Consider `Expect-CT`

**Comment by Knight1** [comment]
Is this for the Interface or the API? Because curl does not support expect-ct afaik. 
There are many providers out there for reporting like this, any conceptual ideas?

**Comment by peterthomassen** [comment]
We don't need [CSP reporting](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to), as our web site's requirements don't change much, and the overhead of maintaining a reporting endpoint is much higher than taking a look at the CSP header when there's a new requirement.

`Expect-CT` is obsolete due to [SCT Auditing which our certificates do support](https://community.letsencrypt.org/t/expect-ct-sct-and-lets-encrypt/142612/2).
