### ISSUE TITLE
api: duplicate RR contents in RRsets

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#211]
- check whether RFCs allow duplicate RRs in RRsets (TXT?) -- I think it is not allowed
- if indeed not allowed, change API validation accordingly

**Comment by andrewtj** [comment]
> * check whether RFCs allow duplicate RRs in RRsets (TXT?) -- I think it is not allowed

That's right, from [RFC 2181](https://tools.ietf.org/html/rfc2181#section-5):

```
   Each DNS Resource Record (RR) has a label, class, type, and data.  It
   is meaningless for two records to ever have label, class, type and
   data all equal - servers should suppress such duplicates if
   encountered.  It is however possible for most record types to exist
   with the same label, class and type, but with different data.  Such a
   group of records is hereby defined to be a Resource Record Set
   (RRSet).
```

**Comment by andrewtj** [comment]
Comparing data in canonical wire format (canonicalising all names) is probably the least error-prone way of checking for equality as there's many representations for the same data in DNS's ASCII presentation format.

It's also important to get this correct as if duplicate data does make it through to the wire DNSSEC validators can consider it a protocol error.

**Comment by nils-wisiol** [comment]
We do have [some tests](https://github.com/desec-io/desec-stack/blob/a0a1ce50b641dbfc771f66709e3d8a2341b956e5/test/e2e/spec/api_spec.js#L581) for this, but I'm not 100% certain they cover all "duplicate content" cases.

**Comment by andrewtj** [comment]
@nils-wisiol I'm not sure what parser is being used but depending on its capabilities there's a few things to consider:

* Escapes including `\DDD` escapes representing byte literals. eg: the name `a.2` could be written `\097.2`.
* Generic presentations for datatypes, eg: `TYPE16` is another way of writing `TXT`.
* Case sensitivity in names and mnemonics, eg: `a.2` and `A.2`, `TXT` and `txt`.
* Quoted character strings, eg: `"a" "b"` is the same as `a b`.
* Insignificant whitespace. eg: `"a" "b"` is the same as `"a"  "b"`
* Parenthesis, eg `"a" "b"` is the same as `"a" ( "b" )`.

**Comment by nils-wisiol** [comment]
> Comparing data in canonical wire format (canonicalising all names) is probably the least error-prone way of checking for equality as there's many representations for the same data in DNS's ASCII presentation format.

Shall do this!
