### ISSUE TITLE
api: improve handling of malformed update IP addresses

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#23]
Currently, the API accepts malformed strings for IPs in the update request, which causes the pdns API to error, which in turn causes an internal server error.

Input IP addresses should be checked for correct syntax before sending them to pdns, however the API should also be able to deal with error returned from the pdns API.

**Comment by nils-wisiol** [comment]
If a pdns update fails, we return 500 to the client, as pointed out above. This can happen when pdns cannot update due to high transaction volume on the database server, for instance.

Proposal: Start database transaction for the api database, then wait for result of pdns api call, then commit/rollback api database transaction. What do you think, @peterthomassen ?

**Comment by peterthomassen** [comment]
sounds like a good proposal!

**Comment by peterthomassen** [comment]
@nils-wisiol Before fixing the API error codes, let's fix the IP validation stuff. (Just a note why I'm not working on the error codes for now.)

**Comment by nils-wisiol** [comment]
fixed by #36 
in particular, here: https://github.com/desec-io/desec-stack/pull/36/files#diff-d93a995458c0f3a31fb831c4f43b5d27R176

**Comment by peterthomassen** [comment]
@nils-wisiol What's been fixed in #36 is the database transaction business, but not the treatment of malformed IP addresses. For that, we have https://github.com/desec-io/desec-stack/commits/20170113_IPvalidation which does not have a PR yet -- right?
