### ISSUE TITLE
Deleting a user owning domains causes error 500

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#251]
- We do not want to allow account deletion if the user still has domains.
- Currently, such cases raise error 500 because the deletion breaks due to foreign key constraint violation on the database level.
- We should catch the exception and return a reasonable status code, e.g. 409 Conflict

@nils-wisiol How should we do this? I suppose the exception needs to be caught/transformed into another one in `User.delete()`, and maybe caught again in the view. Also, do we want to check this condition already when the user requests a deletion code (at issue time, not at use time)?

**Comment by nils-wisiol** [comment]
My proposal returns 409 for both the request to issue the delete action code as well as when a valid delete code is used. I figured that's a conservative choice as the number of domains does not influence code validity.
