### ISSUE TITLE
API invalidly (?) allows setting MX to an IP address (followed by a dot)

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#285]
Only IPv4 works; for IPv6 like `::1.`, pdns says "non-hostname content ::1."

Seems like IPv4 fulfills DNS format, as a result of which this issue is allowed to happen.

**Comment by andrewtj** [comment]
An ASCII IP address with trailing dot like `1.2.3.4.` is a valid hostname (albeit some folks frown on hostnames starting with numbers) so while it is incorrect until `4` becomes a TLD, it is valid. `::1.` on the other hand is a valid domain name but not a valid hostname.
