### ISSUE TITLE
Lift 500 byte length restriction for RR.content

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#334]
Context:
- introduced here https://github.com/desec-io/desec-stack/commit/591e15ec687f349daa0966f5ad7bc21a78639789
- due to https://github.com/PowerDNS/pdns/issues/8012
- users are noticing https://talk.desec.io/t/openpgpkey-record/28

**Comment by renne** [comment]
The 500 byte limit hits DKIM-RRs, too.

**Comment by My1** [comment]
https://github.com/PowerDNS/pdns/issues/8012 -> seems fixed

**Comment by peterthomassen** [comment]
Will be fixed in pdns-auth 4.4.0, but it has not been released yet. We will deploy the fix once it is officially available.
