### ISSUE TITLE
Support apex aliasing

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#348]
Some use cases, especially cloud deployments, require ALIAS/ANAME records, which enable CNAME-like behavior on the apex. It works by having the authoritative server do a lookup and inject up-to-date A/AAAA responses when queried for A/AAAA record types.

pdns support (https://doc.powerdns.com/authoritative/guides/alias.html):
> Starting with the PowerDNS Authoritative Server 4.0.0, DNSSEC ‘washing’ of ALIAS records is supported on AXFR (not on live-signing). Set outgoing-axfr-expand-alias to ‘yes’ and enable DNSSEC for the zone on the master. PowerDNS will sign the A/AAAA records during the AXFR.

We could implement this by increasing the serial and triggering an AXFR from nslord to nsmaster whenever the underlying A/AAAA records have changed. The trigger can, for example, be done in a Celery job which regularly (every `RRset.ttl` seconds) compares the value of A/AAAA records as returned by nslord (up-to-date) vs. nsmaster (currently published).

DNSSEC behavior during the background lookup probably depends entirely on what the resolver does that is configured at nslord (`resolver` setting). We can configure it such that DNSSEC is honored `iff` the ALIAS target has it configured, but we cannot easily provide a switch for deSEC users to decide how they would like lookup validation to be done.

Optionally, we can provide an API endpoint which immediately triggers an ALIAS freshness check (the one done by Celery), to facilitate post-deployment hooks in the cloud and the like.

More ideas welcome.

Note: Ensure in the trigger job that loops can't happen (apparently, pdns doesn't have logic to detect this.)

**Comment by zyrill** [comment]
I would welcome a solution with a sane default and optionally usable additional functionality like a refresh hook. From a user's perspective, I really only wanted to host a website - all the knowledge I needed because I deployed a CDN and needed ANAME records I would happily have avoided having to gain. Same goes for all the selector1-ourdomain._domainkey.ourdomain.onmicrosoft.com and cdnverify.ourdomain.azureedge.net settings. They behave unintuitively, to say the least - this obviously isn't your problem or fault, but if you would provide a solution, that might be an interesting USP of deSEC imho.

**Comment by peterthomassen** [comment]
This problem will be solved by the new HTTPS record type, which is currently being standardized and pushed by Akamai and Google. We thus expect support on major browsers/platforms in the mid-term.

The record type solves a more general issue, and the use case described in this issue is a special case. You can find the details [here](https://tools.ietf.org/html/draft-ietf-dnsop-svcb-https-00#section-9.2).

Our backend is based on PowerDNS which will support these records in its 4.4 release, which will appear this winter. We are planning to support it in our API asap.

**Comment by peterthomassen** [comment]
@zyrill We fixed this by adding support for the HTTPS/SVCB record types.

You can configure an alias for a web application on the main domain by creating an `HTTPS` record with content `0 some.alias.target.example.com.`. Chrome will start experimental support in February, and Apple/Mozilla are also on board.

**Comment by Tone866** [comment]
> This problem will be solved by the new HTTPS record type

But this only solves it for websites. Not ssh and other stuff.
