### ISSUE TITLE
Access Nameservers during Development

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#352]
docker-compose exposes ports to the name servers via `docker-compose.dev.yml`, but this change stops connections: https://github.com/desec-io/desec-stack/commit/09ede83056f9b0e10c67035ddace26bd060a152b#diff-861d4dd8bb85a30abf4a91efa8d9bd5fR14

**Comment by nils-wisiol** [comment]
also check nsmaster

**Comment by peterthomassen** [comment]
Your talking about accessing pdns for making DNS queries, right? The change you linked should only affect the pdns API, not the DNS interface.

**Comment by nils-wisiol** [comment]
Oh right my bad. I meant API access, which is also exposed in the "Dev" config, but then denied by pdns

**Comment by peterthomassen** [comment]
Then I think we should not expose the pdns API on the dev host anymore, because the alternative would be to come up with a complicated ACL in the pdns config, which I'd like to avoid (bugs to complexity etc.). The pdns API can always be accessed from within the API container, and in a dev setup it's very simple to enter the container.

Also, the API was only exposed for nslord, not nsmaster, so the above proposal is already the current state for nsmaster.

Ok for you?

**Comment by nils-wisiol** [comment]
With docker networking, this procedure complicates development while providing no security benefits, right?

Either way, either docker-compose config or pdns needs an updated config

**Comment by peterthomassen** [comment]
`nslord` is in the `rearlord` network, and `nsmaster` is in `rearmaster` and `rearreplication`. Without the `webserver-*` settings, the pdns API would be accessible from these networks. The security benefit would be to avoid that, limiting access to the `rearapi_ns` network (which is a network shared by the two pdns containers and `api`).

I think it's always a good idea to whitelist network connections, even in the presence of authentication mechanisms.

**Comment by nils-wisiol** [comment]
Fair points, then let's find another way of access. Maybe dev mode can overwrite an env variable or something.

**Comment by peterthomassen** [comment]
This issue was opened saying what should be done, but not what the use case is. I'm not sure what it is -- can you enlighten me? (Otherwise, I'd vote for closing it.)

**Comment by nils-wisiol** [comment]
Running e2e2 in pycharm depends on this

**Comment by nils-wisiol** [comment]
> Running e2e2 in pycharm depends on this

actually, running e2e2 in pycharm depends on DNS access, i.e. udp/53, tcp/53 access to nslord and/or nsmaster, not on ns api access.

**Comment by nils-wisiol** [comment]
nslord is already available via ${DESECSTACK_IPV4_REAR_PREFIX16}.0.129 when using docker-compose.test-e2e2.yml.
