### ISSUE TITLE
Add web-interface for zone management

### ISSUE THREAD

**Issue by renne** [desec-io/desec-stack#358]
The API is nice but if you just want to check/edit some static records using the API is of no comfort and a no-go for John Does.

I suggest to offer a HTML5/ECMAscript web-interface based on the API to view/add/update/delete RRs. This would also allow to add assistants for complex records like SRV, NAPTR, TLSA, SMIMEA, OpenPGPkey, etc.

**Comment by peterthomassen** [comment]
Yep, that's a very important point. In fact, it's one of our next items on the roadmap. We'll first release a very simple GUI targeted at dynDNS users, and in the next step come up with the full GUI. You can track progress of the first part here: https://github.com/desec-io/desec-stack/projects/3

**Comment by andreasnuesslein** [comment]
Ahoyhoy you heroes,

when I read about your service on heise yesterday I absolutely loved the project so I looked into it, realized you didnt have a GUI yet and started building one with svelte. Half a day of svelte later I double-checked github.com and https://talk.desec.io/ and realized you are (kinda?) working on a GUI too - can I help? Have you decided on a framework yet?

**Comment by peterthomassen** [comment]
@andreasnuesslein As discussed in private, have decided on using Vuejs. A basic version of the GUI has been released in the meantime, and I am now finishing record management.

@renne We think that assistants for fancy record types are a very good idea. We track record separately in #390.
