### ISSUE TITLE
API: Limit API Tokens to IP Addresses and/or routes

### ISSUE THREAD

**Issue by Knight1** [desec-io/desec-stack#363]
HI!

I would like to automate the whole LE stuff like before in Google Cloud with API tokens restricted to the Servers IP.
And (Best case) with access to some fancy stuff like only allow POST,PUT AND DELETE on _acme-challenge (subdomain) like OVH API https://api.ovh.com/console/#/domain

What do you think?

**Comment by peterthomassen** [comment]
hi! Thanks for those great ideas. We already have a ticket for this topic, and are collecting ideas there. Would you mind commenting at https://github.com/desec-io/desec-stack/issues/347? Thanks!
