### ISSUE TITLE
www: Add security.txt

### ISSUE THREAD

**Issue by Knight1** [desec-io/desec-stack#365]
https://securitytxt.org

Is there a GPG key and/or security@ ?

**Comment by nils-wisiol** [comment]
Yes, we accept mail at security at desec io; GPG key IDs can be found in the git log and are `646BF1C9530E4350` and `5203651ED2F34D28`. My public key can be retrieved from the usual key servers or nils-wisiol.de (scroll to bottom of page or use the [deep link](http://www.mi.fu-berlin.de/inf/groups/ag-idm/members/3_Mitarbeiter_innen/Nils-Wisiol/public-key.txt)).

@peterthomassen Where can your public key be found?

**Comment by peterthomassen** [comment]
You can discover my key via `gpg -v --auto-key-locate clear,wkd,nodefault --locate-key peter@thomassen.io`. This key is also valid for my desec.io address.

**Comment by Knight1** [comment]
We should put that on the website with the .well-known/security.txt if you like an agree.

**Comment by peterthomassen** [comment]
Sure! I allowed myself to assign you ;-) Let me know if that was not right.
