### ISSUE TITLE
Migrate legacy domains to use ECDSA P-256 for DNSSEC

### ISSUE THREAD

**Issue by Darkspirit** [desec-io/desec-stack#370]
https://dnsviz.net/d/desec.io/dnssec/
Currently you use a 2048 bit RSA KSK and a 1024 bit RSA ZSK.
RSA is not recommended at all for DNSSEC. Remaining usage is legacy with a need to migrate away from. RSA was one of the strongest arguments against DNSSEC. If you use RSA, you unnecessarily make DNS responses super large. If RSA is used at all in some other use case, nothing below 2048 bits should be used.
(For Websites you should prefer ECDSA P-256 or P-384 as well. RSA should ideally no longer be used.)

You could either use a P-256 KSK and P-256 ZSK:
https://dnsviz.net/d/cloudflare.com/dnssec/

Or directly use one P-256 CSK:
https://dnsviz.net/d/powerdns.org/dnssec/

https://twitter.com/AFNIC/status/1222904523481444362 (https://www.afnic.fr/en/resources/blog/resolutions-for-2020-afnic-goes-elliptic.html)
https://blog.cloudflare.com/dnssec-done-right/
https://twitter.com/VDukhovni
(Also worth a read: https://blog.cloudflare.com/black-lies/)

**Comment by peterthomassen** [comment]
Thanks for your observations! In fact, RSA usage is also a legacy at deSEC, and only "old" zones use it. Zones that were created more recently use P-256 CSK, for example this one: https://dnsviz.net/d/desec.org/dnssec/

We are planning to roll over legacy domains eventually, but haven't made a precise plan yet.

**Comment by nils-wisiol** [comment]
[newer version of pdns implement algorithm rollover](https://github.com/PowerDNS/pdns/commit/3391829938b4544a59c93c4734532ce2fdc311bf), so we first need to upgrade nslord (also related to #371)

**Comment by nils-wisiol** [comment]
telemetry from [RFC8145](https://tools.ietf.org/html/rfc8145) may be helpful in this

**Comment by nils-wisiol** [comment]
Better do this sooner than later: the 1024bit RSA keys should be replaced asap by academic consensus, but let's also mention that BSI says it's probably fine until 2021. [Wander, M. Measurement survey of server-side DNSSEC adoption. in 2017 Network Traffic Measurement and Analysis Conference (TMA) 1–9 (2017). doi:10.23919/TMA.2017.8002913.]

**Comment by peterthomassen** [comment]
I checked and the only legacy domains are desec.io, dedyn.io, and a bunch of child zones of dedyn.io. This means we can do the rollover without involving any of our users.

**Comment by peterthomassen** [comment]
We rolled the algorithm for domains under dedyn.io. We'll roll the algorithm of dedyn.io itself, and of desec.io, during the next days.

**Comment by peterthomassen** [comment]
The algorithm rollovers for desec.io and dedyn.io have been completed; all zones now use ECDSA curve P-256.
