### ISSUE TITLE
Support AXFR Import via API for Convenient Migration

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#373]
Maybe via a POST `api/v1/domains/example.com/axfr/` or something. dnspython may be able to do the parsing. Delete everything and replace? Also, ignore the SOA? What if DNSSEC records are present? (Suggestion: silently ignore)

**Comment by peterthomassen** [comment]
introduced via 51f7a33afbe60bbdc2b8c847d4046046e69c2674
