### ISSUE TITLE
api: rework Domain.is_registrable

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#382]
- outsource different check stages into individual methods
- only permit zones that don't have a parent or child zone owned by another user (modulo direct children of public suffixes)
- think about reserved names

**Comment by nils-wisiol** [comment]
Let's also improve error messages, as users sometimes do not know why a specific name isn't available. The current message, "This domain name is unavailable because it is already taken, or disallowed by policy.", is very unspecific.

**Comment by peterthomassen** [comment]
It's true that the message is unspecific, but how does it help the user to know the reason? I am asking because establishing a data structure to communicate the reason(s) seems rather cumbersome, while the benefit is unclear to me. Do we know that this is a problem, from user perspective?

Besides, the "already taken" part in a sense applies to three cases:
- the domain itself is taken
- a parent domain is taken (i.e. the parent tree occupies the subtree in question, and is "taken")
- a child domain is taken (i.e. the domain in question would not gain full control of its corresponding DNS tree, as a subtree is taken)

In each case, "something" is taken. Maybe we can improve the message to say that the domain name "conflicts with an existing zone". That would be correct, and rather simple.

The only other cases we block are public suffixes or reserved names (currently only `.internal`), for which I think it is indeed fine to say "disallowed by policy" without further explanation.

**Comment by peterthomassen** [comment]
In #395, I changed the error message to be a bit more accurate (elaborating on zone conflicts), and added more precise policy information to the docs.
