### ISSUE TITLE
Fix dotenv setup for webapp

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#396]
Remove envsubst construction and inject env variables directly using docker compose and `VUE_APP_` env variable name prefix (see #384)

**Comment by nils-wisiol** [comment]
ping @andreasnuesslein

**Comment by andreasnuesslein** [comment]
Hm.. I'm not sure: Will you tackle this? Should _I_ create a PR that is specifically just for this and decoupled from the README #397 ?

**Comment by nils-wisiol** [comment]
I'm working on this right now so that you can continue on #397 :+1:
