### ISSUE TITLE
Updating IP Address Immediately After Zone Creation Fails

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#40]
Setting the `arecord` field on a domain immediately after it's creation fails and causes a 500 server error.

Steps to reproduce (`bash`):

    export DESEC_USERNAME=baz@bar.com
    export DESEC_PASSWORD=123password
    export DESEC_DOMAIN=baz.dedyn.io

    http POST https://desec.nils.dedyn.io/api/v1/auth/register/ email:=\"${DESEC_USERNAME}\" password:=\"${DESEC_PASSWORD}\"
    export DESEC_AUTH=$(http POST https://desec.nils.dedyn.io/api/v1/auth/login/ email:=\"${DESEC_USERNAME}\" password:=\"${DESEC_PASSWORD}\" | grep auth_token | egrep -o [a-z0-9]{40})
    http POST https://desec.nils.dedyn.io/api/v1/domains/ Authorization:"Token ${DESEC_AUTH}" name:=\"${DESEC_DOMAIN}\"
    http PATCH https://desec.nils.dedyn.io/api/v1/domains/${DESEC_DOMAIN}/ Authorization:"Token ${DESEC_AUTH}" arecord:=\"127.1.1.1\"

The reason appears to be that [this](https://github.com/desec-io/desec-stack/blob/0a7386a6da298bd5094362dc1b2def1e1505f2ca/api/desecapi/pdns.py#L52) request is made without pdns already having a SOA record for the domain (pdns reply: `{"error": "No SOA found for domain 'baz.dedyn.io.'"}`).

I cannot pinpoint where exactly the SOA record is added later (any idea, @peterthomassen?); it appears to have something to do with the [cron job](https://github.com/desec-io/desec-stack/blob/a7618f03e1f3b3178ba337fd035b878dfcdd1f0e/nslord/cronhook/secure-zones.sh).

The error will cause any update to be lost (as would be expected by the client); however with the next non-erroring `POST` to that domain any previous error will be recovered, so in many cases this is not an urgent problem.

**Comment by peterthomassen** [comment]
This issue only occurs in the `20170415_notify` branch, right?

If so, the reason is: We create zones with type `NATIVE`, and later switch to `MASTER`. Only from that point on, notify is a valid operation.

(Btw, we do not create the SOA record ourselves; it is created by pdns during the CREATE operation. I think the pdns error message you quoted above is misleading: I imagine that domain existence is tested by looking for an SOA record in the database, but there's probably a WHERE clause limiting the search to `MASTER` zones, so that the SOA record is not found when it's still `NATIVE`.)

**Comment by nils-wisiol** [comment]
The issue also occurs with 9d1abe9052a52be6f02a092690d19cb1014e46f3, however a DNS request before POSTing is needed, as illustrated below:

    export TESTNAME=wql
    export DESEC_USERNAME=${TESTNAME}@bar.com
    export DESEC_PASSWORD=123password
    export DESEC_DOMAIN=${TESTNAME}.dedyn.io

    http POST https://desec.nils.dedyn.io/api/v1/auth/register/ email:=\"${DESEC_USERNAME}\" password:=\"${DESEC_PASSWORD}\"
    export DESEC_AUTH=$(http POST https://desec.nils.dedyn.io/api/v1/auth/login/ email:=\"${DESEC_USERNAME}\" password:=\"${DESEC_PASSWORD}\" | grep auth_token | egrep -o [a-z0-9]{40})
    dig @localhost -p 5321 $DESEC_DOMAIN
    http POST https://desec.nils.dedyn.io/api/v1/domains/ Authorization:"Token ${DESEC_AUTH}" name:=\"${DESEC_DOMAIN}\"
    http PATCH https://desec.nils.dedyn.io/api/v1/domains/${DESEC_DOMAIN}/ Authorization:"Token ${DESEC_AUTH}" arecord:=\"127.1.1.1\"


Also make sure to deactivate abuse limits while testing.

**Comment by peterthomassen** [comment]
As discussed, our environment does not produce DNS requests to nslord, so the issue does not occur in practice.
