### ISSUE TITLE
deSEC settings for pfSense

### ISSUE THREAD

**Issue by AndreasAZiegler** [desec-io/desec-stack#425]
I'm using pfSense and would like to set up deSEC. I tried several setting but didn't manage to get it working. I appreciate any help. The last think I tried are the following settings:
As username I used the domain
As password I used the token
![pfSense-deSEC](https://user-images.githubusercontent.com/6949508/88622016-1c855180-d0a2-11ea-82ca-e96e410ea7fc.png)

I get the following error in the logs:

Jul 28 01:01:02 | php-cgi |   | rc.dyndns.update: DynDns (): Dynamic Dns: cacheIP != wan_ip. Updating. Cached IP: 0.0.0.0 WAN IP: 77.59.185.127
-- | -- | -- | --
Jul 28 01:01:02 | php-cgi |   | rc.dyndns.update: Dynamic DNS custom (): _update() starting.
Jul 28 01:01:02 | php-cgi |   | rc.dyndns.update: Sending request to: update.dedyn.io
Jul 28 01:01:02 | php-cgi |   | rc.dyndns.update: Dynamic DNS custom (): _checkStatus() starting.
Jul 28 01:01:02 | php-cgi |   | rc.dyndns.update: phpDynDNS (): (Error) Result did not match.  [<html>^M <head><title>301 Moved  Permanently</title></head>^M <body>^M  <center><h1\>301 Moved  Permanently</h1\></center>^M  <hr><center>nginx</center>^M </body>^M  </html>^M ]

**Comment by nils-wisiol** [comment]
deSEC doesn't allow authentication over plain text, try setting the update URL to https://update.dedyn.io

**Comment by AndreasAZiegler** [comment]
Then I get ```/services_dyndns_edit.php: phpDynDNS (): (Error) Result did not match. [Invalid basic auth token] ```

**Comment by nils-wisiol** [comment]
Make sure you are using a token for authentication, not your account password. Tokens can be generated after loging on deSEC.io

**Comment by AndreasAZiegler** [comment]
I do use the token. Does the name related to the token id need to be something specific? It's currently ```login``` which seems to be the default name.

**Comment by nils-wisiol** [comment]
The return code is indicating that you use `Basic` auth, but you should use `Token` auth. Details are in the docs: https://desec.readthedocs.io/en/latest/dyndns/update-api.html#rest-api-method-http-token-authentication

(If you want to keep using `Basic` auth, you'd need to encode the token accordingly.)

**Comment by AndreasAZiegler** [comment]
Thanks for pointing me towards that page.

The way, I understand it, given the (limited) pfSense interface, I have to use the **Query string method (discouraged)** and append ```?username=...&password=...``` to the update URL resulting in ```https://update.dedyn.io?username=...&password=...```.

Is this interpretation correct?

**Comment by nils-wisiol** [comment]
Your router seems to support `Basic` auth, as indicated by your post above. Using your domain name as username and your token as password should work, but you receive "[Invalid basic auth token]". My guess is that the token could be too long or there is a typo in the domain name. Unfortunately, without further information, I can't help here. Try double-checking username and password, if it doesn't help, ask at support@desec.io with further information like your IP address or domain name.

**Comment by AndreasAZiegler** [comment]
I got this answer via email and want to share it as it actually solved my issue.

>Our token values do not have the form 82733565-feb5-4909-8e80-19a1b83dab85.
This is the format of the IDs of our tokens. For authentication, you need
to send the token value, not the token ID.

>The token ID is needed to distinguish tokens, as the token name field is
optional (and you can also use the same token name several times).

>You cannot look up the value of an already existing token in our web
interface. In fact, we do not store the values of our token in clear
text.

>The token value is only displayed once when you create a token. In the
web interface, it is displayed in a notification at the bottom of the
screen. (If you use the REST API manually, the token value is contained
in the response body when you issed a token create request.)

>So best way forward probably is to delete your pfSense token in our
web interface, and create a new one. Then take a look at the value
displayed at the bottom of the screen, and copy it to your pfSense
configuration.
