### ISSUE TITLE
api: enforce rate limits per domain (not per account)

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#434]
The dns_api_write rate limit is currently low to prevent issues from concurrent updates to the same domain. As rate limits are currently enforced per user, the limit is stricter than intended and also affects quick sequential updates to independent domains.

We should introduce a per-domain rate limit for DNS write operations, and then relax or remove the per-user limit.

The issue was brought up here: https://talk.desec.io/t/request-was-throttled/120/6

**Comment by Eisfunke** [comment]
If I'm not mistaken this is somewhat of a duplicate of #525 and was fixed with https://github.com/desec-io/desec-stack/commit/a4b28ffa21775dc2ecdc9f8f5c3361b4c574064e

**Comment by peterthomassen** [comment]
Indeed! Thanks a lot for noticing; back when I implemented the functionality, I wasn't aware of this issue I had previously created.
