### ISSUE TITLE
Add SMIMEA resource record

### ISSUE THREAD

**Issue by renne** [desec-io/desec-stack#436]
Hi,

it's great to have OpenPGPKey resource records with deSec! :+1:
As companies tend to use S/MIME certificates for email encryption I suggest to also support [SMIMEA](https://tools.ietf.org/html/rfc8162) resource records.

**Comment by peterthomassen** [comment]
This depends on SMIMEA support for dnspython. @nils-wisiol created a pull request for it, https://github.com/rthalley/dnspython/pull/578 Once there is a dnspython release that includes it, we'll support it.
