### ISSUE TITLE
Introduce CDS/CDNSKEY for Managed Domains

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#443]
Setting of CDS/CDNSKEY records [can support](https://tools.ietf.org/html/rfc8078#section-3) deployment of DS records to the registry in various degrees, depending on policy. Adoption on the registry side is still limited.

**Comment by peterthomassen** [comment]
@ulrichwisser You can track progress on CDS/CDNSKEY support here.
