### ISSUE TITLE
Comparison of Replication Mechanisms

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#452]
This issue is to document and discuss how data replication between desec-stack and various frontends could take place. The replication mechanism is divided in three different responsibilities:

- Crypto: the layer ensuring data integrity and confidentiality
- Diff: how changes are determined, including addition and deletion of zones
- Transfer: how new and changes zones are transferred

Crypto/Diff/Transfer | Partial Zone Transfer | Bandwidth for No-Op Run | Time for No-Op Run | Bandwidth for Full Sync | Time for Full Sync | Bandwidth Typical Sync | Time Typical Sync | 
-- | -- | -- | -- | -- | -- | -- | -- 
SSH / rsync (file list) / rsync | yes | :negative_squared_cross_mark: 230kB+, O(#zones)? | :heavy_check_mark:  1-7s | :heavy_check_mark: :1st_place_medal:  ~50% total master file size | :heavy_check_mark: 10-15s | :negative_squared_cross_mark: 230kB+ changes | :heavy_check_mark: <15s
VPN / mariadb / mariadb | yes(?)| n/a | n/a | a lot? | <5 mins | ? | :heavy_check_mark: seconds
VPN / Merkle Tree / AXFR | no | :heavy_check_mark: <1kB, O(1) | :heavy_check_mark: minimal | :heavy_check_mark: total AXFR size | :negative_squared_cross_mark: ~45min | :heavy_check_mark: <1kB + changes | :heavy_check_mark: <15s[1]
TLS / Gluster / Gluster | yes | n/a | n/a | ? | ? | ? | ?
SSH / git / git | yes | :heavy_check_mark: ~12kB [2] | :heavy_check_mark: :1st_place_medal: 1-4s | :heavy_check_mark: :1st_place_medal: ~50% total zone size | :heavy_check_mark: 10-15s | :heavy_check_mark: :1st_place_medal: 370kB[3] | :heavy_check_mark: 3-6s
VPN / rsync (single file zone list) / AXFR | no | :heavy_check_mark: <1kB O(1) | :heavy_check_mark: <5s | ? | :negative_squared_cross_mark: ~45mins | :heavy_check_mark: O(1) + changes | :heavy_check_mark: <15s[1]

[1] May increase for very large zones unless replaced with IXFR
[2] measured on the wire. For comparison, SSH handshake and shell prompt: also 12kB
[3] one small zone deleted, dedyn.io (5MB master file) "rewritten"

Feel free to add columns/rows!

# Open Problems / Advantages
- How to measure time/bandwidth for a typical run? A definition for typical could be: 
    - Each zone is updated at least once per week, i.e. for each 10k zones there is 1 zone update per minute
    - Some zones are updated regularly, i.e. once per day, some zones are almost never updated
    - So let's say typical means 1.5 updated zones per minute, with one zone having a large change (50%+ in master file format) and one having a small change (e.g., one line in master file format)

## AXFR Transfer
- When doing all key rollovers at once, this my inhibit manual zone updates during this time, as the AXFR queue is very long

## SSH & rsync
- :heavy_check_mark:  ~~unreliable connection, packet loss~~ seems to be handled well by rsync (no failure in ~10 trials)
- :negative_squared_cross_mark:  high bandwidth usage for inremental file list
- :heavy_check_mark: eliminates need for VPN

## mariadb replication
- how to react to changes? timestamp column required?
- note: this may behave much nicer than earlier as pdns is changing fewer rows now when a zone is updated
- random crashes without recovery?

## Merkle Tree
- :negative_squared_cross_mark: high implementation complexity (I'm guessing there is no library available for such tasks, but who knows, maybe worth looking into)
- :negative_squared_cross_mark: does not support partial zone transfers (how about file-list based rsync? IXFR?  :eyes: )
- :heavy_check_mark: top metrics for no-op runs
- need to deal with packet loss --> no, can use TCP for everything

## Gluster (or any other replication fs)
- :negative_squared_cross_mark: high configuration complexity
- :negative_squared_cross_mark: kernel support required
- :heavy_check_mark: can handle huge amounts of data
- propagation latency?
- :heavy_check_mark: eliminates need for VPN

## git
- how to truncate git history?

**Comment by nils-wisiol** [comment]
# deSEC Frontend Implementation

deSEC frontend consists of two essential parts: the replicator client and the nameserver.

## replicator client

The replicator client uses this central update mechanism:

```python3
diff = RsyncDiff()  # or MerkleTreeDiff(), RsyncSingleFileDiff(), GitDiff(), ...
transfer = AXFRTransfer()  # or RsyncTransfer(), ...
nameserver = BINDNameserver()  # or KnotNameserver(), ...

while True:
    zones_added, zones_modified, zones_deleted = diff.obtain()
    for z in zones_added:
        d = transfer.get(z)
        nameserver.add(z, d)
    for z in zones_modified:
        d = transfer.get(z)
        nameserver.updated(z, d)
    for z in zones_deleted:
        nameserver.delete(z)
    throttle()
```

Here, three modules are used. `diff` and `transfer` need to take care of their respective integrity and confidentiality.

### diff
`diff` obtains the modifications since last time checked and returns lists of zones that have been added, modified, and deleted. The comparison to the last time we checked means that `diff` needs to have some sort of local storage.

### transfer
`transfer` implements some way to obtain zone contents. This may be connected to the storage backend of `diff`, e.g. in the case of rsync.

### nameserver
`nameserver` manages the nameserver attached to the replicator. It lets the nameserver know which zones have been added, modified, or deleted. If added or deleted, zone content is provided.

## nameserver

Needs sensible configuration for attacks and so on; zones will be added via the `nameserver` module of the replicator client.

**Comment by peterthomassen** [comment]
Nice pseudocode!

I think deletion should be done before addition and updates, since it's very fast, so "it gets more changes done quicker".

> The comparison to the last time we checked means that `diff` needs to have some sort of local storage.

That's not strictly required. `diff` can forget what has been determined previously, and just compare remote (master) to the local status quo. That may lead to transfers being initiated multiple times, but that may even be important in case a transfer does not succeed.

**Comment by nils-wisiol** [comment]
> I think deletion should be done before addition and updates

The first version I wrote did that, but I thought what if a zone is listed as modified and deleted...

> That may lead to transfers being initiated multiple times, but that may even be important in case a transfer does not succeed.

Right, `diff` somehow needs to be aware of the result of the `transfer` operations

**Comment by nils-wisiol** [comment]
When using replication with git, we need to take care that git history doesn't grow indefinitely, while at the same time, we would like that clients can `git pull` anytime. 

## Fallback Solution

Whenever `git pull` fails, the frontend will be instructed to delete local data and `git clone` a new copy of the repository. This will take 10-15s with the current data, plus latency for communication with the nameserver.

Open Problem: In this process, zones deleted in the meantime will be overlooked

If git history at the desec-stack becomes a problem, the desec-stack git repository can be deleted and recreated. Clients will fail to pull and resort to a new clone.

## Solution

The server periodically cleans git history by using the shallow feature of git. For a commit `$COMMIT` a little older than the maximum supported sync period, the server runs

```
git rev-parse $COMMIT > .git/shallow
git reflog expire --expire=now --all                        
git gc --prune=now
```

This will convert the server's git repository into a shallow one based on `$COMMIT` and remove all prior history. All clients that know `$COMMIT` will be able to pull as regular. (Also, the shallowness does not propagate through a pull, so clients need to do their own housekeeping.) If clients do not know `$COMMIT`, they will receive

```
warning: reject refs/remotes/origin/master because shallow roots are not allowed to be updated
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

on `git pull`.

The client can drop almost all local git history periodically, as this won't interfere with updates (in the above code, set `$COMMIT` to `HEAD~3` or so).
