### ISSUE TITLE
[Feature Suggestion] IPFS gateway

### ISSUE THREAD

**Issue by lomereiter** [desec-io/desec-stack#453]
Hello there, thanks for your service! I wondered if the following might pique your interest.

To begin with, [IPFS](https://github.com/ipfs/go-ipfs) is a global p2p version-controlled filesystem that can be used to host static websites, among other use cases. An [IPFS Gateway](https://docs.ipfs.io/concepts/ipfs-gateway/) is commonly used to allow access via traditional HTTP: the A/AAAA record for the domain points to the gateway, which then reads the path in IPFS from the specially crafted TXT record ([DNSLink](https://dnslink.io/)), resolves the path and returns the file contents. (To be clear, a gateway is passthrough, the contents are read from a nearby IPFS node but can be cached on the gateway.)

The tricky part is how to enable HTTPS. One option is to run one's own IPFS gateway, or at least a reverse proxy, but that defeats the purpose: it's static content after all, and for most people the gateway would have to run in the cloud because of CGNAT and IPv6 not yet being supported by all ISPs. The other is to use the [Cloudflare gateway](https://www.cloudflare.com/distributed-web-gateway/) (yay, decentralized internet! /s), which is the only one that automatically issues TLS certificates, but obviously requires using Cloudflare DNS as well. Note: IPFS developers [declined](https://github.com/ipfs/infra/issues/212#issuecomment-347387180) to add such functionality to their ipfs.io gateway,  on the grounds that this would reduce IPFS visibility, which is fair enough.

This is where deSEC could fill the gap and provide a community-driven alternative.

In case the above didn't make much sense, here's a link to a blog post describing how the whole thing works, including Cloudflare:
https://medium.com/pinata/how-to-easily-host-a-website-on-ipfs-9d842b5d6a01

**Comment by peterthomassen** [comment]
As far as I understand, it is already possible today to set up the TXT records needed for DNSLinks at deSEC.

As far as the IPFS Gateway is concerned, I'm a bit confused. Can you elaborate why such a gateway should be hosted by a DNS operator?

**Comment by lomereiter** [comment]
Never mind. I bought into the hype at some point, but now don't see much point myself. Closing this issue, will consider reopening if it's still relevant in 2025.
