### ISSUE TITLE
api: custom name dyn zones

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#46]
Checklist:
- [ ] implementation
- [ ] unit test

**Comment by nils-wisiol** [comment]
People often ask me about this.

**Comment by nils-wisiol** [comment]
We have this now, [talk.desec.io has a short how to](https://talk.desec.io/t/dyndns-and-lets-encrypt-using-custom-domain/17/4). This could become feature of our webapp or be added to the docs.

**Comment by peterthomassen** [comment]
This is slightly different, right? `CNAME` only works on subdomains, not on the zone apex, so if you have custom domain, you can't use the domain name itself as a dynDNS domain (subdomain only).

**Comment by nils-wisiol** [comment]
The manual on talk.desec.io also covers the case without cname.

**Comment by nils-wisiol** [comment]
superseded by #393
