### ISSUE TITLE
subname display truncated in web app

### ISSUE THREAD

**Issue by unuseless** [desec-io/desec-stack#476]
When you add DNS records to a domain in the web app and the subname is quite long (more than 20 characters), the following happens:

After saving you can't see the complete subname anymore, so you can't check for errors.

**Comment by nils-wisiol** [comment]
The problem with the automatic scaling of column width in v-data-table
    is that all our contents (even the ones you cannot edit) are input
    element. Input elements must have a defined width -- as opposed to
    other elements, they do not grow with content. Now which width
    should we assign? I couldn't find a satisfactory solution, so this
    just adjusts the pre-defined column widths a bit.
