### ISSUE TITLE
Support for Handshake names

### ISSUE THREAD

**Issue by rithvikvibhu** [desec-io/desec-stack#479]
Hi.
I'm trying to host a zone for a Handshake name on deSEC. From what I can tell, it is possible to add second-level domains (`my.whatevername.`), but not the name itself (`whatevername.`).

It's great that deSEC does not limit to domains with an ICANN tld like other services and hopefully will be able to host records for just the name too.

Adding 2 domains (say `apple.whatevername.` and `orange.whatevername.`) is possible right now as the NS required to be added in the registry is the same (`ns1.desec.io` and `ns2.desec.org`).
The problem is when setting up **DS** records. 2 different domains on deSEC ask different DS records to be added.

So if deSEC allows adding the name itself (`whatevername.` in the example), then a common DS record would work for all "sub" domains.

To be clear, deSEC does not have to interact with Handshake at all, only allow the name to be added, not just SLDs.

What is Handshake?

> Handshake is a UTXO-based blockchain protocol that manages the registration, renewal, and transfer of DNS top-level domains (TLDs). Our naming protocol differs from its predecessors in that it has no concept of namespacing or subdomains at the consensus layer. Its purpose is not to replace DNS, but to replace the root zone file and the root servers.

Official website: https://handshake.org/
Documentation: https://hsd-dev.org/

**Comment by peterthomassen** [comment]
Registration of [public suffixes](https://publicsuffix.org/) through the API is disabled as it would have the side-effect of reserving the whole subtree for the public suffix owner. For example, if you maliciously registered `co.uk`, then nobody could register `anything-else.co.uk` because `co.uk` is under your authority. As all top-level domains qualify as a public suffix, they currently can only be registered manually by deSEC support.

Having said that: Let's say we grant you to register `whatevername.`, and later ICANN delegates `whatevername.` to some registry. How should the conflict be resolved?

**Comment by rithvikvibhu** [comment]
>if you maliciously registered co.uk, then nobody could register anything-else.co.uk because co.uk is under your authority

>Let's say we grant you to register whatevername., and later ICANN delegates whatevername. to some registry. How should the conflict be resolved?

I think we can break this into 2 questions:

#### 1. Name ownership can be transferred much more easily than ICANN TLDs (think registries themselves changing hands).

This is a similar problem to how Google Voice lets anyone link their phone number. When adding a phone number (handshake name), you verify it with an SMS (TXT record).
There won't be any problem even if the phone number is given to someone else. The zone remains hosted on deSEC, but the new owner would have changed the NS records to their own service.
Suppose the new owner wants to use deSEC, they simply prove by updating/creating the TXT record, and the zone is transferred to their deSEC account.

#### 2. Conflict between ICANN TLDs and Handshake names (and their subzones)

As regular domains are not verified before hosting zones, I think this is similar to how those cases are handled. What does deSEC do when 2 accounts want to register the same zone?

If it's a manual intervention, then then the same could be done for handshake names too. It would be up to deSEC to decide which zone to host (`bob.name` from ICANN or `bob.name` from Handshake). At this point, given Handshake's presence currently, giving regular domains preference over Handshake names is understandable.

This should be feasible as registries manage their own nameservers and conflict is unlikely (but can still be handled as ^).

I can't speak for all, but Route53 manages this by assigning different nameservers. So if two parties want to host the same zone, they can do so in different nameservers (ns-806.awsdns-36.com, etc.)
Now obviously, this does increase complexity, and not sure if it's even possible for deSEC, I just wanted to mention how some other services do it.

**Comment by rithvikvibhu** [comment]
Also, I'd like to mention that my interest in hosting the root name is because of DNSSEC (and DANE). The blockchain supports a limited number of records, so for every SLD, adding 3 DS records will add up quickly.

I'm don't know a lot about DS, but would it be possible to for a set of DS records to be enough for multiple deSEC domains? (say I add `apple.name` and `orange.name`)

**Comment by nils-wisiol** [comment]
Currently, every zone on deSEC gets individual keys, hence requires individual DS records. It's true that this adds up quickly, but so far we've managed to maintain several ten-thousand DS records for our dynDNS service dedyn.io. So, at least for starters, this shouldn't be a problem. We also considering to [expose some of the key management to the user](https://talk.desec.io/t/ksk-key-rollover-and-ds-update/162), which could in effect lead to choosing the same key for several zones. Another option we also consider is [importing pre-signed zones](https://talk.desec.io/t/dnskey-and-rrsig/126/2), which would also enable you to use the same DS for all child zones. However, neither of those is currently a development priority, although you're of course welcome to join the discussion or contribute code.

For registering a TLD name on desec.io, please contact the desec.io support. Note that we have no plans for supporting conflicting names across different nameservers.

I skimmed through the Handshake website, but at first sight I couldn't find the reason why it needs a TLD. So maybe it would be an option to host it under `handshake-test.dedyn.io`? Anyways, in the spirit of Handshake's idea, note that you always have the option of running your own, decentralized instance of desec-stack.

**Comment by rithvikvibhu** [comment]
>but so far we've managed to maintain several ten-thousand DS records for our dynDNS service dedyn.io

I was referring to the size limit for records on the handshake blockchain, where the root records are stored (and where deSEC's NS and DS records will need to be added).


>However, neither of those is currently a development priority, although you're of course welcome to join the discussion or contribute code.

Both options sound promising, I'll be sure to try them out if and whenever they are ready.


>I skimmed through the Handshake website, but at first sight I couldn't find the reason why it needs a TLD. So maybe it would be an option to host it under handshake-test.dedyn.io?

The point of handshake is to allow anyone to own TLDs (names) like `http://nb`. It serves as an alternative root to ICANN.


>Anyways, in the spirit of Handshake's idea, note that you always have the option of running your own, decentralized instance of desec-stack.

Yeah, I guess self-hosting a nameserver is the last resort. In fact, a simple lightweight dns server will do.


>For registering a TLD name on desec.io, please contact the desec.io support

Will do, thanks!

**Comment by nils-wisiol** [comment]
> > but so far we've managed to maintain several ten-thousand DS records for our dynDNS service dedyn.io
> 
> I was referring to the size limit for records on the handshake blockchain, where the root records are stored (and where deSEC's NS and DS records will need to be added).

What's the size limit for those? DS records deSEC-hosted zones are quite industry-standard and should hence fit it, unless I'm missing an important point here.

**Comment by rithvikvibhu** [comment]
Guess I'm not being clear enough. The _number_ of records that can be stored on the chain for a name/tld is limited. Not the size of each record. Nothing wrong with deSEC DS records.

I can't find the exact number of records, but it definitely wouldn't scale with many slds (`x.name`, `y.name`, etc.). That's why I was curious about the common DS records.

**Comment by nils-wisiol** [comment]
Without knowing the details of Handshake, I'm assuming it would be sufficient to add the DS records for `name`, instead of adding all DS records for the second-level domains. Once the DS records for `name` are added, authenticity of DNS information of `x.name` can be proved by going through the DNSSEC signature chain.

If that's a misunderstanding or somehow not supported by Handshake, then you'd have to wait for the above-mentioned features of deSEC or resort to a different choice.

Let me know if you have further questions or comments!

**Comment by peterthomassen** [comment]
There's still an aspect that I'd like to understand better:

> #### 2. Conflict between ICANN TLDs and Handshake names (and their subzones)
> As regular domains are not verified before hosting zones, I think this is similar to how those cases are handled. What does deSEC do when 2 accounts want to register the same zone?

If someone registers a zone at deSEC, that is of no consequence in itself. A delegation (domain registration) is required so that the zone is actually in effect. If someone owns a domain name and claims the corresponding zone at deSEC, we will verify the identity and assign the zone to that person. As the zone at deSEC was not previously "in production", nothing would break.

In contrast, if we allow registering a Handshake TLD, it will be in Handshake production. If ICANN later assign the same TLD to some registry, then we will have to a) either reject that, keeping the Handshake TLD operational, or b) accept that, breaking the Handshake TLD.

This conflict is intrinsically different from the non-Handshake scenario. I see no way out of collisions between the DNS root and an "alternative root". To not break things, it seems to me that we therefore should stay away from assigning TLDs which may later lead to a conflict that cannot be resolved in a non-breaking manner.


All that is, of course, completely independent from securing the root with some Blockchain technique. The point of contention here is the conflict potential in claiming TLD ownership.

**Comment by rithvikvibhu** [comment]
> If someone owns a domain name and claims the corresponding zone at deSEC, we will verify the identity and assign the zone to that person. 

This is manual and not automated, right? Because anyone can add zones without verifying it right now. In fact, I added one handshake sld (and gonna try the DS inheritance @nils-wisiol suggested in https://github.com/desec-io/desec-stack/issues/479#issuecomment-731100122).


> If ICANN later assign the same TLD to some registry, then we will have to a) either reject that, keeping the Handshake TLD operational, or b) accept that, breaking the Handshake TLD.

That is true. ICANN has completed the first phase of the new gTLD program and is currently ["reviewing and carrying out a policy development process"](https://newgtlds.icann.org/en/reviews/faqs). As no new gTLDs will be assigned for a while, Handshake hopes to gain traction during this time.

As a DNS hosting service, it is understandable to stick with the ICANN root as that's what most resolvers look for right now.


>This conflict is intrinsically different from the non-Handshake scenario. I see no way out of collisions between the DNS root and an "alternative root". To not break things, it seems to me that we therefore should stay away from assigning TLDs which may later lead to a conflict that cannot be resolved in a non-breaking manner.

As @peterthomassen mentioned for non-handshake names, "If someone owns a domain name and claims the corresponding zone at deSEC, we will verify the identity and assign the zone to that person."

Why not let non-ICANN slds(/tlds) stay as they are right now?
If in the future, a new TLD is released by ICANN, all zones (whether a root name or an sld) of that tld hosted on deSEC can have a grace period to verify (with a TXT record). The release schedule by ICANN will provide ample time to inform zone holders and will only happen when new TLDs are released (which is not happening right now).

Basically, yes to verification with ICANN root, but only when the TLDs are released.

I see 2 ways to do this:
1. ICANN releases a TLD `.name`. User A already has a handshake sld `bob.name` and is hosting with deSEC.
  a. deSEC has a grace period for when _all_ `.name` and `*.name` zones need to be verified by setting a TXT record in the ICANN root.
  b. User A may want to purchase `bob.name` from ICANN as they already have the same name on handshake. They do so within the grace period and verify it with deSEC. The zone continues to stay with deSEC.
  c. If User A does not verify within the period, the zone is removed. deSEC wants the whole zone cleared to make way for regular domains.

2. ICANN releases a TLD `.name`. User A already has a handshake sld `bob.name` and is hosting with deSEC.
  a. deSEC warns User A to either get verified within the grace period or risk losing the zone anytime a new user wants the zone.
  b. If User B wants to host their ICANN domain `bob.name`, they can do so (by verifying it). User A's zone will be deleted as they had not verified it in the grace period.
  c. If no user wants to host ICANN's `bob.name` (if bob is a rare word, etc.), User A continues to host `bob.name` with the constant risk of the zone being deleted.

If the owner of the handshake sld `bob.name` wants to purchase `bob.name` from ICANN once `.name` is released, they can do so and continue with the same service (after verifying the ICANN domain).

Names that are not TLDs can continue to be hosted. I mention this because most handshake names are very unlikely to make it as a tld (that's a lot of them, check out https://namebase.io/domains/ to get an idea), they can continue to host on deSEC without any conflict.
