### ISSUE TITLE
api: allow to postpone captcha to email verification stage

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#489]
To facilitate scripted sign-ups (e.g. in [Nextcloud VM](https://github.com/nextcloud/vm)), we should allow signing up without solving the captcha. The captcha then has to be solved upon verifying the email address. After verifying the email address with a valid captcha, and given that a dynDNS domain was provided during sign-up, an API token is displayed so that users can proceed with their configuration.

Caveat: Captchas currently have one shot and are invalidated if entered incorrectly. We would like to keep that, so that they can't be solved via brute force. If that happens, we should delete the pending registration, and a new sign-up request would be required. @nils-wisiol Do you agree?

@enoch85 Tagging you to be able to follow the issue. Also, would you be able to cope with issuing a new sign-up request in case the captcha is entered incorrectly?

**Comment by enoch85** [comment]
> issuing a new sign-up request in case the captcha is entered incorrectly?

If there is a way to check that with your API, sure. Otherwise it might be hard.
