### ISSUE TITLE
UI: inconsistency after DNS record deletion

### ISSUE THREAD

**Issue by xopham** [desec-io/desec-stack#497]
Description:
When deleting an entry in the UI for managing DNS records, the UI will mix up the records.

1. initial state
![Screenshot from 2021-01-04 15-09-35](https://user-images.githubusercontent.com/37963496/103544069-c82b9c80-4e9f-11eb-8749-fa1d25b9423c.png)
2. after deletion
![Screenshot from 2021-01-04 15-09-58](https://user-images.githubusercontent.com/37963496/103544083-cfeb4100-4e9f-11eb-9a92-c04df67d8656.png)
3. after refreshing the browser
![Screenshot from 2021-01-04 15-10-30](https://user-images.githubusercontent.com/37963496/103544103-d7aae580-4e9f-11eb-8a42-8dd907c53d91.png)

In the above flow, the actual entry for `txt1` was moved by deletion into `txt2` which's own entry was dropped. After refreshing (F5 or CTRL+R) the inconsistency is gone and all entries are as expected.

The above flow demonstrates that this does not cause an actual inconsistency or error in the data. However, only the UI displays this inconsistency and may confuse users. Also this could cause further problems when updating an inconsistent entry.

**Comment by nils-wisiol** [comment]
Same problem can occur when changing the sort-order of the table. The content field seems to miss some value updates.

**Comment by nils-wisiol** [comment]
The problem here is that [Record.vue::update](https://github.com/desec-io/desec-stack/blob/master/webapp/src/components/Field/Record.vue#L171) is not called when the content property is changed.
