### ISSUE TITLE
Why is API running on python 3.5?

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#51]

**Comment by peterthomassen** [comment]
Python 3.5 was the most up-to-date version when the api Dockerfile was written. I hardcoded the minor version number to avoid surprises from incompatible changes, especially as this could happen with `docker-compose build` immediately before deployment.

Python 3.6.0 was released in December 2016, but Python 3.5 is not dead (3.5.3 was released in January this year). In fact, it will be supported with security fixes for at least 5 years from the 3.6 release onwards (see https://docs.python.org/devguide/devcycle.html).

If there is some argument why we should upgrade (like, if we need a 3.6 feature), there's of course nothing stopping us from doing so.
