### ISSUE TITLE
api: add throttling scope and rate to throttled response

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#536]
e.g.

```
{"detail":"Request was throttled (dns_api_write_rrsets, 30/h). Expected available in 3109 seconds."}
```

**Comment by peterthomassen** [comment]
The point of this is that to get told which throttle one was hit by, ideally with the rate. If the rate can't be given, the scope name would still help to find the rate in the docs.

1. To make this change, we need to override each view's `throttled()` method, passing a `detail` argument along that so far is not there:
    ```python
    def throttled(self, request, wait):
        raise exceptions.Throttled(wait, detail=f"Request was throttled ({self.throttle_scope}).")
    ```
2. It's a bit more difficult to pass the actual (list of) rates (such as `[30/h]`), as they are currently not accessible in that context:
    1. Either initialize a `Throttle` instance again with the right attributes and then call `parse_rate()`. As that's also done during the throttling decision, this would be duplicate work.
    2. Hook into the throttling decision and save the rates from within the context where they are available. This can be done by making the request object an attribute of `ScopedRatesThrottle` (it is passed to `allow_request()` where we can assign it to `self.request`). When the throttle actually takes effect, the `wait()` method will later be called, and at this point the rates are available in `self.duration`, which we could then assign to `self.request.throttle_duration` or something, and use in the above exception detail.

The question about (2) is really whether we think that's too hacky -- may or may not be, but at least it is a change in one place (after one has done (1)).

A complication arises from (1) though, because we'll have to do this for *all* our rate-limited views, *or* patch DRF's `exceptions.Throttled` class (... perhaps not), *or* introduce a new intermediate class or mix-in into our views' class hierarchy. As far as I can see, both the intermediate class and the mix-in would have to be declared separately for the various DRF classes from which our views inherit; that is, it would still be many places and easy to get wrong in the future.

@nils-wisiol Do you think the extra usability (see beginning of the post) justifies the hassle? It's not difficult, just not very smooth w.r.t. to maintainability.

**Comment by nils-wisiol** [comment]
I think this should be done in DRF, or not at all. The maintainers there can also better speak for what implications these changes might have.

**Comment by peterthomassen** [comment]
Fair. DRF doesn't have a related issue, and I don't really think it's worth bothering for now.
