### ISSUE TITLE
Verisign DNSSEC Analyzer URL returns undefined instead of Domain

### ISSUE THREAD

**Issue by Knight1** [desec-io/desec-stack#544]
Somehow 'domain' seems to be undefined. 

https://github.com/desec-io/desec-stack/blob/cd086dda09bbc27b82f9d18b320bb5a63863fd3b/webapp/src/views/DomainSetup.vue#L125

**Comment by peterthomassen** [comment]
Thanks for the report!

I cannot reproduce the problem. Can you please provide steps how to reproduce the issue?

**Comment by Knight1** [comment]
Hey Peter!

Login, go to Domains, click on 'i' for your best Domain, scroll down to "3. Check Setup"

This is Firefox 89 for macOS x86.

![image](https://user-images.githubusercontent.com/1573278/121823282-93b8d980-cca4-11eb-9b4d-6582c8260225.png)
