### ISSUE TITLE
api: IP update/dynDNS API rate limits

### ISSUE THREAD

**Issue by Eisfunke** [desec-io/desec-stack#560]
The rate limit for the dynDNS-API [is limited to 1 request per minute](https://github.com/desec-io/desec-stack/blob/a4b28ffa21775dc2ecdc9f8f5c3361b4c574064e/api/api/settings.py#L112) with the comment "anything above 1/min is a client misconfiguration".

That is only true for single domains though, e.g. I'd like to update multiple domains at once each time when my IP changes, and would have to wait a minute between every update for each domain. That means for my 10 domains that would take at least 10 minutes to update all of them.

(CNAME records can't quite remedy this as they can only be used on subdomains and may not coexist with other records on the same domain)

I suggest one of these solutions:

- changing the dynDNS rate limit to be domain-scoped, like `dns_api_write_rrsets` is
- generally increasing the rate limit for dynDNS to something like 10/min
- changing the rate limit to something like 60/h instead so that the infrequent "bursts" occuring during IP changes can be handled while keeping the overall rate unchanged.

What do you think?

**Comment by peterthomassen** [comment]
The first solution sounds great! We did not think of it initially as most users just have one dynDNS domain. but it makes perfect sense.

I don't like the other two proposals because we really have a significant number of users with broken setups who send five, sometimes more redundant requests in a row. We would like to signal to them that something's wrong in their setup. (The usecase of keeping subdomains in sync is easily and also more elegantly (atomic updates) covered by setting up a CNAME.)

I'll add a commit to your PR.

**Comment by Eisfunke** [comment]
Thank you very much for the quick answer and fix!

If I'm not mistaken though, a CNAME record for subdomains is not always possible as CNAME records can't coexist with any other records on the same subdomain (if I correctly remember the RFC someone quoted on some StackOverflow answer I read once :D).

So if one need other records on the same subdomain, one needs to update it separately (e.g. for me that is especially apperent with a wildcard, I can't make that a CNAME as I need other records on some subdomains).

Maybe the rate limit could be increased to something like 2 or 3/min additionally? I think that would still catch broken setups while giving a little more wiggle room. If not, that's fine too, I get that what I'm describing is probably a very niche case :D

**Comment by peterthomassen** [comment]
> If I'm not mistaken though, a CNAME record for subdomains is not always possible as CNAME records can't coexist with any other records on the same subdomain

Yes, that's correct.

As to your use case, I think it's too complex for the rather simplistic dynDNS update interface. If you need to update several records, you can do so atomically in one go, without running into a rate limit, by using the [bulk features of our REST API](https://desec.readthedocs.io/en/latest/dns/rrsets.html#bulk-operations). An update should be as simple as sending a curl request with a JSON payload that has your IP addresses embedded in the right places.

This approach helps us defend better against accidental misconfigurations (as explained above), and also keeps our load down even in legitimate use cases. (We sign your zone on each write request, and when you use a bulk request, that gives our nameserver a break.)
