### ISSUE TITLE
Width of input fields (for CAA) randomly changes

### ISSUE THREAD

**Issue by rugk** [desec-io/desec-stack#562]
## STR

1. Click the button in the web interface to add a record…
2. It looks like this:
  ![grafik](https://user-images.githubusercontent.com/11966684/124932990-ce900200-e003-11eb-85b6-9fe131db44ea.png)
3. Now enter `0` as the flag (what you always need to do :sweat_smile:)

### What happens

Suddenly, the input/width of the field you've entered the flag is much smaller:
![grafik](https://user-images.githubusercontent.com/11966684/124933139-f1bab180-e003-11eb-963b-014f356532a8.png)

### What should happen

The width should always stay the same?
Either the flags field must be also small beginning from the start. If you remove the `0` again after you did the previous STR's, you can see how that could look like:
![grafik](https://user-images.githubusercontent.com/11966684/124933585-4bbb7700-e004-11eb-9b35-381970d4a265.png)

…or it should just keep it's initial (big) width.

## System

Firefox 98.0.2
Fedora Workstation 34

**Comment by peterthomassen** [comment]
Seems like this is no longer the case.
