### ISSUE TITLE
SOA Mname is invalid

### ISSUE THREAD

**Issue by carbongreat13** [desec-io/desec-stack#580]
The Mname in the SOA record is get.desec.io, but this is an invalid value.
It should be either ns1.desec.io or ns2.desec.org.

**Comment by carbongreat13** [comment]
See also: https://www.dnsinspect.com/desec.io/10591570

**Comment by peterthomassen** [comment]
The finding is a false positive, see https://talk.desec.io/t/invalid-soa-record/68/4.
