### ISSUE TITLE
Could you please enable Expect-CT?

### ISSUE THREAD

**Issue by carbongreat13** [desec-io/desec-stack#583]
For added security, why not enable Expect-CT on desec.io?

**Comment by peterthomassen** [comment]
An attacker who is in the position to get an illegitimate certificate into their hands is also in the position to remove the Except-CT header, so there is no added security.

**Comment by peterthomassen** [comment]
> According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT, Expect CT has likely become obsolete earlier this year:

https://github.com/desec-io/desec-stack/issues/203#issuecomment-871856757
