### ISSUE TITLE
aaaa record not recognized

### ISSUE THREAD

**Issue by pepa65** [desec-io/desec-stack#586]
I am trying to add an aaaa record with the value `fe80::216:3cff:fef1:92a9` and it gets rejected with "This field must contain an IPv6 address." Is there a workaround or syntax I can use to get this to take??

**Comment by nils-wisiol** [comment]
Which method are you using to set the AAAA record? I've just used the web interface at desec.io to set the record for test.example.dedyn.io and haven't had any issue.

**Comment by pepa65** [comment]
Thanks. Not sure what went wrong, but I got one now with the same (intended) content.
