### ISSUE TITLE
Add Webapp to Feature List on Landing Page

### ISSUE THREAD

**Issue by solbu** [desec-io/desec-stack#599]
Me and a friend is looking for a new dns hosting after learning that gratisdns.dk is moving all of their 200.000 domains into one.com, and one of the promising solutions is desec.
But the «Docs» link on the front page only discusses how to do things using curl and the API.

Is it really not possible to manage domains (creating domain, updating records, adding or removing records) by logging in to the website?
I am not prepared to create a user without knowing that one does not have to start creating our own scripts just to manage domain names. :-)

May I suggest you create documentaion on how to use the webinterface to manage domains,if that is a supported feature.

**Comment by nils-wisiol** [comment]
We do have webapp-based record management. [Creating an account is easy](https://desec.io/signup), and you can start playing around with our GUI immediately after confirming your email address.

**Comment by nils-wisiol** [comment]
I've realized that we do not advertise our web app on the landing page. We should add something that mentions we have a webapp for domain and record management :)

**Comment by nils-wisiol** [comment]
ping @peterthomassen
