### ISSUE TITLE
desec.io is unusable for blind people 

### ISSUE THREAD

**Issue by solbu** [desec-io/desec-stack#600]
A friend of me registered an hour ago and was planning to move hos dns hosting here, but he cannot use the website.
He uses a braille device in order to read computer outputs. He also use a screen reader which reads out loud the text.

There is a yellow button with a big PLUS sign on it, but it is not labled with what id does, so he has no way of knowing if it adds a domain, adds a dns record, deletes a record or deletes the entire domain.

The buttons on the webinterface need to be labled in the html tag with a description of what it does.

**Comment by solbu** [comment]
I forgot to add that my friend is blind, and hence he cannot actually see. :-)

**Comment by nils-wisiol** [comment]
We have no experience and limited resources to make desec accessible, but we are certainly interested in improving on this end. Could you point us to some resources saying what exactly is required to make it work for your friend?

See also #472

**Comment by solbu** [comment]
> Could you point us to some resources saying what exactly is required to make it work for your friend?

An example is the yellow + button on the domain management page.
That is either an image or just a circle with yellow color with two overlapping lines which makes a cross, making it look like a plus sign, using html magic.

In the button tag which adds a new domain, you can add an «aria-label» tag inside the button tag.
Most people would be able to infer visually that this button will add a new domain. A blind person using assistive technology will hear or see nothing. The «aria-label» tag explicitly tells them what the button will do.

So in this concrete example, the button for adding a new domain currenty reads:
```
<button data-v-a9f93a2e="" type="button" class="v-btn v-btn--fab v-btn--has-bg v-btn--round theme--dark v-size--small primary" id="create">  
<span blah blah></span>  
</button>
```

Inside that «button» tag, simply just add this tag: «aria-label="Add new domain"»
Which would look like this:
```
<button aria-label="Add new domain" data-v-a9f93a2e="" type="button" class="v-btn v-btn--fab v-btn--has-bg v-btn--round theme--dark v-size--small primary" id="create">  
<span blah blah></span>  
</button>
```

**Comment by peterthomassen** [comment]
Aria-labels are part of #472; let's have the discussion there. Happy to accept pull requests for this improvement.
