### ISSUE TITLE
Login Credentials Gone upon Navigation

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#619]
from https://talk.desec.io/t/login-session-expires-when-navigating-the-site/468:

> When logged in on the [desec.io](http://desec.io/) site, and i navigate to some of the other menus, and when i return to the DNS overview, i am no longer logged in. Thats very annoying when i have to login every time i navigate somewhere else. You state that i am logged out by inactivity, but this is a matter of seconds after logging in.
>
> Please also consider the ability to save login credentials in the browser. Almost all sites have that capability, and its up to the user if they think about security.
>
> I use momentarily the chrome browser on a mac computer.

I confirmed the issue with Chrome on Ubuntu.

**Comment by peterthomassen** [comment]
Is this when navigating e.g. to the donation page or imprint, or does this also happen on a navigation path within the area only accessible after log in?

In other words, did we break something, or is this the way it has been since the start?

**Comment by nils-wisiol** [comment]
My trials only showed that this happens when navigating outside the login-protected pages.

**Comment by peterthomassen** [comment]
I'll push a fix soon -- but just for the record, this was intentional: https://github.com/desec-io/desec-stack/blob/ddf39b1303ef5814177a39b37b93a7594b5fc558/www/webapp/src/router/index.js#L186-L190
