### ISSUE TITLE
IPv6 prefix change for whole (sub-)domain

### ISSUE THREAD

**Issue by JeGr** [desec-io/desec-stack#673]
This is a feature request of something I stumbled upon checking a DynDNS setup with one of our customers, that uses another DynDNS service. The feature works as following:

* customer can create (sub)domain with the service (like with your dedyn.io domains)
* customer can create multiple A/AAAA entries within this subdomain
* customer can update A/AAAA records via API

and with a special IPv6 option in their API:

* customer can update the prefix-part (64bit) of ALL AAAA records within the subdomain AT ONCE

So if I have a domain with desec.io that's named `example.dedyn.io` and I create several hostnames in it like `abc.example.dedyn.io` and put A and AAAA entries in it, that's quite a normal thing that is working right now.
But now I have a stupid rotating IPv6 prefix e.g. attached to my DSL line that rotates every 24h like my IPv4 address that makes IPv6 a big PITA to manage, as I would have to update not only my IPv4 entries in the zone, but every IPv6 entry, too. Or perhaps there are quite a few IPv6 only entries. I'd have to refresh every single one as the address part (last 64bit) will stay the same but the prefix part has changed.

So if there were a flag or parameter that could be set up that I could use combined with the already availabe `preserve` parameter, I could simply send a request to the API for ´example.dedyn.io` to refresh the AAAA prefix part of ALL entries at once and every IPv6 AAAA record in the zone would be updated to the new prefix.

I know that's "greedy" as perhaps there could be a few entries that perhaps have another prefix and shall remain in theirs but for the start I'd have no problem for the implementation to be "domain wide" as with dedyn one could easily set up a 2nd dedyn.io or other managed domain for only that purpose. And for every customer that has to deal with the german stupidity of "dynamic IPv6 prefixes" it would be an immensely nice tool to simply refresh the prefix of multiple hostnames with one simple API call to the whole domain!

Looking at the clock I hope my ramblings made sense, otherwise feel free to ask. I'd be happy to help test such a feature as I'm struck with a double load of it, having two WANs on the homelab, that both use that stupid dynamic prefix nonsense that simply make working with IPv6 a hot and burning mess :/

Cheers
\jens

**Comment by peterthomassen** [comment]
Thank you for your report, Jens! This has been a long-standing issue (#13), but we haven't got around to working on it, and nobody has sponsored it. My estimate is that it'll likely sit for a while if nobody takes it up. Would you like to contribute a PR?

Closing in favor of #13.
