### ISSUE TITLE
api: Confusing test name testManualIPv6

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#73]
@nils-wisiol I came across this dynDNS test https://github.com/desec-io/desec-stack/blob/1238a2e72c2ae6f9603b86fdd1eff32d04398413/api/desecapi/tests/testdyndns12update.py#L195 which makes sure that authorization via `password` query parameter works.

The name of it is `testManualIPv6` though. Was it supposed to test something IPv6-related? I tried to track it down historically, but it's been like this since this respository exists.

**Comment by peterthomassen** [comment]
Similar with https://github.com/desec-io/desec-stack/blob/1238a2e72c2ae6f9603b86fdd1eff32d04398413/api/desecapi/tests/testdyndns12update.py#L126

**Comment by nils-wisiol** [comment]
You're right, it does not seem to do anything related to IPv6. I can't explain what happened here, sorry :)
