### ISSUE TITLE
RRset Value Field doesn't Update with Type

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#739]
When creating a new RRset, the value input field isn't updated with the selected type of RRset anymore. This means that it is harder for the user to input a valid value. (But not impossible.) Similarly, when editing RRsets, the value shown isn't properly annotated.

This looks like it happened when #713 was deployed, @Rotzbua would you be able to take a look? My gut-feeling is that some renaming has gone wrong.

In the screenshot, MX is selected, so there should be separate fields for priority and hostname, but there is only one.

![image](https://github.com/desec-io/desec-stack/assets/1026940/cb88a283-cb41-460c-8854-b7bdced76924)

**Comment by Rotzbua** [comment]
Thanks for the report. Found the bug.
