### ISSUE TITLE
do not load module in itself

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#77]
desecapi django module shouldn't [load itself](https://github.com/desec-io/desec-stack/blob/master/api/desecapi/settings.py#L48).

**Comment by peterthomassen** [comment]
I tried removing this line, but it breaks startup of the app. I'm not sure what the solution is, or even whethre loading `desecapi` is wrong. Can I defer to you, @nils-wisiol ?

**Comment by peterthomassen** [comment]
Looks like we need to create a separate app directory for this. I will look into that next week.

**Comment by nils-wisiol** [comment]
maybe @zervnet knows more about this?
