### ISSUE TITLE
webapp(cli): migration from `vue-cli` to `vite`

### ISSUE THREAD

**Issue by Rotzbua** [desec-io/desec-stack#771]
Following steps are necessary:

- [x] Remove/replace dependencies relying on `vue-cli` #770
- [x] Fix file naming #763
- [ ] `vuelidate`
  - [ ] Migrate `vuelidate` to v2 **OR**
  - [x] Fix `vuelidate` (v0) build process
- [x] Migration to `vite`

**Comment by peterthomassen** [comment]
vuelidate migration also tracked in #649.
