### ISSUE TITLE
www: SSL Labs for desec.io at A-

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#78]
desec.io scores A- in the SSL Labs audit because Forward Secrecy is not supported with some reference browsers. It would be nice to fix this.

**Comment by My1** [comment]
it certainly is a nice thing, but depending on some things it might be advisable to grab the code and compile yourself (or use that docker image) instead of the binaries from their website.

**Comment by peterthomassen** [comment]
fixed by 61a9a3698146234a73f3ccce635d07c5087b5dbc
