### ISSUE TITLE
ISNIC registration

### ISSUE THREAD

**Issue by Mello3vnik** [desec-io/desec-stack#803]
Hi,

I would like to know if it would be possible for desec to register with ISNIC, the Icelandic administrator of the ".is" extension.
.is has some restrictions, including requiring nameservers to register with them in order to be used.

https://www.isnic.is/en/faq#q49

Thanks for your feedback

**Comment by peterthomassen** [comment]
We've been registered with ISNIC for about three years, so everything should work.

If you're experiencing any problems, feel free to reopen or email support.
