### ISSUE TITLE
Create endpoint for atomic multi-updates

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#83]
The API should have an endpoint that accepts updates to several RR sets that are applied atomic.

After implementation, the existing rrset endpoint and dyndns12 endpoint can be special cases of this new endpoint.

Per discussion with @peterthomassen, this new view shall be responsible for organizing correct order of "select for update", "update or create", and so on, removing this code from the models layer.

**Comment by peterthomassen** [comment]
As per discussion with @nils-wisiol, we are planning to implement strict multi-create by `POST`ing a list (i.e., return `409 Conflict` if one of the `POST`ed RRsets already exists), and weak multi-update by `PATCH`ing a list that may also contain items for creation that do not exist yet. All actions are going to be atomic (collective success or failure).

Open questions:
  - duplicate RRsets in the list
  - `PUT` behavior

**Comment by peterthomassen** [comment]
As discussed in person on Wednesday, we will keep the logic of ordering "select for update", "update or create", and so on in `models.py`.
