### ISSUE TITLE
Domains can't be owned by multiple users

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#85]
However, this may be a desirable feature for companies (even small ones perhaps).

**Comment by My1** [comment]
well I would say that there would be still one owning entity/account (not user, as an account can stand for a lot of things), aka the company but it would be able to delegate access down to other accounts

**Comment by peterthomassen** [comment]
ack

**Comment by My1** [comment]
Also there could be multiple types of entities, which differ in what they can or can't do. A "user" for example can do basically anything including creating servers or "organizations" (a meta entity which can own things like domains but can't actually do anything), while a "server" for example can only access the api directly and wouldn't get website credentials, a "user" on the other hand could for example by default have no api keys, but api access would be done over server entities entirely, for the simple reason that they could be easily replaced or revoked

**Comment by peterthomassen** [comment]
Let's wait until someone asks for this.
