### ISSUE TITLE
Blacklisting of public and already registered suffixes

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#88]
Currently, subzone ("more specific zones") can only be created if 1) we do not know the parent zone, or 2) the parent zone is owned by the same user. Otherwise, malicious users could hijack subzones from other users.

This can be improved by

1. integrating the public suffix list. Currently, if someone creates `co.uk`, other users cannot create their zone under `co.uk`.
2. Allow cross-user delegations by checking the `NS` records in the parent domain (with proper subdomain) (or by checking some other setting of the parent domain) -- not required for launch

**Comment by peterthomassen** [comment]
Case 1 would also allow blacking out large IP ranges for reverse DNS.

**Comment by peterthomassen** [comment]
@nils-wisiol Can you please review https://github.com/sse-secure-systems/psl-dns? If fine, we can close this again.

**Comment by nils-wisiol** [comment]
seems legit
