### ISSUE TITLE
Change Update API to not add record for client_ip if ip(s) are passed as query_params

### ISSUE THREAD

**Issue by ryancwilliams** [desec-io/desec-stack#915]
This issue is to fix the issue outlined in this [thread on talk.desec.io](https://talk.desec.io/t/desec-adding-unstable-aaaa-records-when-receiving-ipv4-only-updates-from-dual-stack-clients-running-dyndns2/921)

### The Problem:

Right now the [IP Update API](https://desec.readthedocs.io/en/latest/dyndns/update-api.html) has a undocumented behavior where it will automatically add a record for the client_ip that made the request if the IP of that type was not overridden by one of the query_params. 

If there are no query_params it is correct to use the client_ip and this is documented.

If there are query_params that specify a IPv4 address then the A record is created correctly but if that request was made from a dual stack client over IPv6 then a AAAA record will also be created that points to the client_ip. This is not documented and caused the issues outlined in the thread I linked above, 

This issue affects primarily devices with older DDNS clients like what one would find in a SOHO router. 

Most DDNS clients only update when their IP address changes. Older DDNS clients are not IPv6 aware so they do not update the records when the IPv6 address changes. DDNS Clients that are Ipv6 aware will add query_params that specify a IPv6 address along side the IPv4 address. 

### What I think should happen is:
* **[New behavior]** In the event a IPv4 address OR a IPv6 address is passed in the query_params the value of client_ip should be ignored. **(Optional new behavior)** Any existing A or AAAA records that are not to be changed by this request should be left untouched.
* **[Same behavior as now]** In the event that no IP address is passed in the query_params then the value of client_ip should continue be used to create the record.

**Comment by peterthomassen** [comment]
> Right now the [IP Update API](https://desec.readthedocs.io/en/latest/dyndns/update-api.html) has a undocumented behavior where it will automatically add a record for the client_ip that made the request if the IP of that type was not overridden by one of the query_params.

This is [exactly as documented](https://desec.readthedocs.io/en/latest/dyndns/update-api.html#determine-ip-address-es).

> If there are query_params that specify a IPv4 address then the A record is created correctly but if that request was made from a dual stack client over IPv6 then a AAAA record will also be created that points to the client_ip.

You can set the `myipv6=` query sting parameter to an empty string (or to `preserve`) to adjust that behavior.

> * [New behavior]

Unfortunately, this would be a breaking change, so we can't do it without breaking existing setups that rely on this behavior.

**Comment by ryancwilliams** [comment]
I do not have a dev environment set up for this project so I can not make the changes myself at this time.

I did take a look at the source and found some areas that might be involved with this issue.

This code looks to be used to extract the IP from the query_params:
https://github.com/desec-io/desec-stack/blob/124f3aef0bdb9eac2cefc3fc0c96f7879513c1ab/api/desecapi/views/dyndns.py#L40-L67

This code looks to be used to process the request to the update API endpoint:
https://github.com/desec-io/desec-stack/blob/124f3aef0bdb9eac2cefc3fc0c96f7879513c1ab/api/desecapi/views/dyndns.py#L145-L183

I am open to any advice or assistance. I am willing to make this change in a PR myself but I want to make sure this is not causing any issues.

**Comment by peterthomassen** [comment]
Good research into the code base, those are the right places! :-)

Unfortunately, as explained above, the way to address this at this point is to use the appropriate `myipv4`/`myipv6` parameters to prevent IP address inference using the connection source.

**Comment by ryancwilliams** [comment]
> > Right now the [IP Update API](https://desec.readthedocs.io/en/latest/dyndns/update-api.html) has a undocumented behavior where it will automatically add a record for the client_ip that made the request if the IP of that type was not overridden by one of the query_params.
> 
> This is [exactly as documented](https://desec.readthedocs.io/en/latest/dyndns/update-api.html#determine-ip-address-es).

I see that now. I did not fully understand what that was saying until after I looked at the source code.

> > If there are query_params that specify a IPv4 address then the A record is created correctly but if that request was made from a dual stack client over IPv6 then a AAAA record will also be created that points to the client_ip.
> 
> You can set the `myipv6=` query string parameter to an empty string (or to `preserve`) to adjust that behavior, as described in the docs linked above.
> 

The problem I am experiencing is I have older DDNS clients embedded in devices that are not IPv6 aware. For some of the devices there are newer versions of the DDNS client available that are IPv6 aware but the problem is the device vendors have not updated their code yet to use this.

 > Unfortunately, this would be a breaking change, so we can't do it without breaking existing setups that rely on this behavior.
 
 Based on our conversation I agree with this. 
 
### Related question:
 
Is it possible to block creation of a AAAA record for a specific host? That way if the update endpoint is used to create a AAAA record for that host the record is not created. 

This would allow me to block the AAAA record creation for my devices that have out of date embedded DDNS clients.

**Comment by peterthomassen** [comment]
> I see that now. I did not fully understand what that was saying until after I looked at the source code.

If you have a suggestion for how to improve the wording, a PR would be welcome!

> The problem I am experiencing is I have older DDNS clients embedded in devices that are not IPv6 aware.

If these old clients allow configuring the update URL (which is usually the case), you can fix the problem by manually setting the update URL and including the `myipv6=` parameter.

> Is it possible to block creation of a AAAA record for a specific host?

Nope, that's currently not possible.

**Comment by ryancwilliams** [comment]
> If you have a suggestion for how to improve the wording, a PR would be welcome!

If I come up will better wording I will create a PR. 

> If these old clients allow configuring the update URL (which is usually the case), you can fix the problem by manually setting the update URL and including the `myipv6=` parameter.

That worked for my Ubiquiti devices. Thanks!

Now I still need to figure out a way to do this with [DDCLIENT for Windows](https://www.randomnoun.com/wp/2013/08/19/a-dynamic-dns-client-for-windows/) or find a alternative DDNS client for my Windows machines.  I am open to any recommendations for DDNS clients that work on Windows.

Ill most likely look into seeing if DDCLIENT supports custom URLs and then hope it works on the older version that DDCLIENT for Windows is based on.

> 
> > Is it possible to block creation of a AAAA record for a specific host?
> 
> Nope, that's currently not possible.

Makes sense. Also this will no longer be necessary once I fix my DDNS clients. 

Thanks for your assistance!
