### ISSUE TITLE
Updating (PUT) a record fails because the record already exists

### ISSUE THREAD

**Issue by WhyNotHugo** [desec-io/desec-stack#949]
I am trying to update an existing record.

I am sending a `PUT` HTTP request to `https://desec.io/api/v1/domains/whynothugo.nl/rrsets/anchor/A/` with body:

```json
{
  "domain": "whynothugo.nl.",
  "type": "A",
  "records": [
    "46.23.92.106"
  ],
  "ttl": 3600
}
```

The response is an error 400 with the body:

```
{
  "non_field_errors": [
    "Another RRset with the same subdomain and type exists for this domain."
  ]
}
```

This error doesn't make sense; of course the record already exist, I'm trying to update it. Its existence is a precondition for this API call.

**Comment by WhyNotHugo** [comment]
Thanks, you've made this very clear.

The error message `"Can only be written on create."` is kinda of misleading; the value is _required_, but this error makes me think that it is optional. Considering that it is in the URL, it could well be made optional for this endpoint.

**Comment by peterthomassen** [comment]
The semantics of PUT is to replace the whole resource, so all fields are required. If you'd like to skip fields, use PATCH.

See also https://restfulapi.net/rest-put-vs-post/:
> PUT replaces the resource in its entirety. Use PATCH if the request updates part of the resource.

**Comment by WhyNotHugo** [comment]
It is weird that a read only field is required. I can understand that "all _writable_ fields must be included. This field is unused (the relevant `subname` is defined in the URL).

**Comment by peterthomassen** [comment]
In other contexts (e.g., when creating an RRset), omitting the subname implies the empty subname. Those who've used that aspect of the API might think that omitting it from a PUT request will change the RRset's subname to the empty subname, which is not the case.

To prevent such misunderstandings, we figured explicit is better than implicit. It's not a big problem to include it, as the client has the subname already to assemble the URL.
