### ISSUE TITLE
Add more valid tags for CAA record

### ISSUE THREAD

**Issue by Mello7sh3i** [desec-io/desec-stack#969]
Hey,

I updated my CAA record (issue and iodef), I wanted to add “issuemail”, for S/MIME certificates (https://www.rfc-editor.org/rfc/rfc9495.pdf), but I get a warning saying that the tag is invalid.
The record works anyway, but if it were possible to remove the warning to avoid confusion, that would be nice.
I also recently saw on a test on hardenize.com that there is an “issuevmc” tag, for BIMI certificates, which could be added at the same time.

Thanks for your work !

**Comment by peterthomassen** [comment]
Thanks for the report. Will fix in a few weeks (currently on vacation).

https://github.com/desec-io/desec-stack/blob/7b17d2444bec74de99496d95362b12a051d950cf/www/webapp/src/components/Field/RecordCAA.vue#L9
