### ISSUE TITLE
Set up CNAME for www.*.dedyn.io

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/desec-stack#98]
Every few months, somebody requests that their domain be reachable also on the `www` or `*` subdomain. While `www` is very specific, I'm not sure if wldcard is advisable: We observe many obviously unintended queries (like ip-1-2-3-4.provider.co.uk.username.dedyn.io), and having the wildcard CNAME in place would probably be misleading.

We can also let this sit here until the GUI is ready, and then people can set up whatever they feel is appropriate.

How to proceed? Opinions wanted.

**Comment by My1** [comment]
considering that wilds can only be one label and the most left at the same time, these queries would go into nowhere no matter what.

**Comment by peterthomassen** [comment]
The wildcard in the issue title is meant as a placeholder, not as a wildcard in the DNS sense. Obviously, CNAME subdomain records would have to be specific for each *.dedyn.io domain; that's already necessary because they would each require different values.

**Comment by My1** [comment]
oh I see, but even then I certainly wouldnt roll out a total multi-level wildcard by default. I mean if people wanna have wildcards further below there's always the API, although a single level wild is at least less of a problem.
